.TH "vendor/jetbrains/phpstorm-stubs/superglobals/_superglobals.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/superglobals/_superglobals.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$GLOBALS\fP = array()"
.br
.ti -1c
.RI "\fB$_COOKIE\fP = array()"
.br
.ti -1c
.RI "\fB$_ENV\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_ENV_VARS\fP = array()"
.br
.ti -1c
.RI "\fB$_FILES\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_POST_FILES\fP = array()"
.br
.ti -1c
.RI "\fB$_GET\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_GET_VARS\fP = array()"
.br
.ti -1c
.RI "\fB$_POST\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_POST_VARS\fP = array()"
.br
.ti -1c
.RI "\fB$_REQUEST\fP = array()"
.br
.ti -1c
.RI "\fB$_SERVER\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_SERVER_VARS\fP = array()"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PHP_SELF'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['argv'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['argc'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['GATEWAY_INTERFACE'] = 'CGI/1\&.1'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_ADDR'] = '127\&.0\&.0\&.1'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_NAME'] = 'localhost'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_SOFTWARE'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_PROTOCOL'] = 'HTTP/1\&.0'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REQUEST_METHOD'] = 'GET'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REQUEST_TIME'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['QUERY_STRING'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['DOCUMENT_ROOT'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_ACCEPT'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_ACCEPT_CHARSET'] = 'iso\-8859\-1,*,utf\-8'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_ACCEPT_ENCODING'] = 'gzip'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_ACCEPT_LANGUAGE'] = 'en'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_CONNECTION'] = 'Keep\-Alive'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_HOST'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_REFERER'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTP_USER_AGENT'] = 'Mozilla/4\&.5 [en] (X11; U; Linux 2\&.2\&.9 i586)\&.'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['HTTPS'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REMOTE_ADDR'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REMOTE_HOST'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REMOTE_PORT'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SCRIPT_FILENAME'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_ADMIN'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_PORT'] = '80'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SERVER_SIGNATURE'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PATH_TRANSLATED'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['SCRIPT_NAME'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['REQUEST_URI'] = '/index\&.html'"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PHP_AUTH_DIGEST'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PHP_AUTH_USER'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PHP_AUTH_PW'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['AUTH_TYPE'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['PATH_INFO'] = ''"
.br
.ti -1c
.RI "\fB$_SERVER\fP ['ORIG_PATH_INFO'] = ''"
.br
.ti -1c
.RI "\fB$_SESSION\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_SESSION_VARS\fP = array()"
.br
.ti -1c
.RI "\fB$argc\fP = 0"
.br
.ti -1c
.RI "\fB$argv\fP = array()"
.br
.ti -1c
.RI "\fB$HTTP_RAW_POST_DATA\fP = ''"
.br
.ti -1c
.RI "\fB$http_response_header\fP = array()"
.br
.ti -1c
.RI "\fB$php_errormsg\fP = ''"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$_COOKIE = array()"
@xglobal $_COOKIE array Variables provided to the script via HTTP cookies\&. Analogous to the old $HTTP_COOKIE_VARS array (which is still available, but deprecated)\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_ENV = array()"
@xglobal $_ENV array @xglobal $HTTP_ENV_VARS array
.PP
Variables provided to the script via the environment\&. Analogous to the old $HTTP_ENV_VARS array (which is still available, but deprecated)\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_FILES = array()"
@xglobal $_FILES array @xglobal $HTTP_POST_FILES array
.PP
Variables provided to the script via HTTP post file uploads\&. Analogous to the old $HTTP_POST_FILES array (which is still available, but deprecated)\&. See POST method uploads for more information\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_GET = array()"
@xglobal $_GET array @xglobal $HTTP_GET_VARS array
.PP
Variables provided to the script via URL query string\&. Analogous to the old $HTTP_GET_VARS array (which is still available, but deprecated)\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_POST = array()"
@xglobal $_POST array @xglobal $HTTP_POST_VARS array
.PP
Variables provided to the script via HTTP POST\&. Analogous to the old $HTTP_POST_VARS array (which is still available, but deprecated)\&. \fBhttps://secure\&.php\&.net/manual/en/language\&.variables\&.predefined\&.php\fP\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_REQUEST = array()"
@xglobal $_REQUEST array Variables provided to the script via the GET, POST, and COOKIE input mechanisms, and which therefore cannot be trusted\&. The presence and order of variable inclusion in this array is defined according to the PHP variables_order configuration directive\&. This array has no direct analogue in versions of PHP prior to 4\&.1\&.0\&. See also \fBimport_request_variables()\fP\&. 
.PP
Caution 
.PP
Since PHP 4\&.3\&.0, FILE information from $_FILES does not exist in $_REQUEST\&. 
.PP
Note: When running on the command line , this will not include the argv and argc entries; these are present in the $_SERVER array\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_SERVER = array()"
@xglobal $_SERVER array @xglobal $HTTP_SERVER_VARS array
.PP
Variables set by the web server or otherwise directly related to the execution environment of the current script\&. Analogous to the old $HTTP_SERVER_VARS array (which is still available, but deprecated)\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$_SERVER[ 'argc'] = ''"

.SS "$_SERVER[ 'argv'] = ''"

.SS "$_SERVER[ 'AUTH_TYPE'] = ''"

.SS "$_SERVER[ 'DOCUMENT_ROOT'] = ''"

.SS "$_SERVER[ 'GATEWAY_INTERFACE'] = 'CGI/1\&.1'"

.SS "$_SERVER[ 'HTTP_ACCEPT'] = ''"

.SS "$_SERVER[ 'HTTP_ACCEPT_CHARSET'] = 'iso\-8859\-1,*,utf\-8'"

.SS "$_SERVER[ 'HTTP_ACCEPT_ENCODING'] = 'gzip'"

.SS "$_SERVER[ 'HTTP_ACCEPT_LANGUAGE'] = 'en'"

.SS "$_SERVER[ 'HTTP_CONNECTION'] = 'Keep\-Alive'"

.SS "$_SERVER[ 'HTTP_HOST'] = ''"

.SS "$_SERVER[ 'HTTP_REFERER'] = ''"

.SS "$_SERVER[ 'HTTP_USER_AGENT'] = 'Mozilla/4\&.5 [en] (X11; U; Linux 2\&.2\&.9 i586)\&.'"

.SS "$_SERVER[ 'HTTPS'] = ''"

.SS "$_SERVER[ 'ORIG_PATH_INFO'] = ''"

.SS "$_SERVER[ 'PATH_INFO'] = ''"

.SS "$_SERVER[ 'PATH_TRANSLATED'] = ''"

.SS "$_SERVER[ 'PHP_AUTH_DIGEST'] = ''"

.SS "$_SERVER[ 'PHP_AUTH_PW'] = ''"

.SS "$_SERVER[ 'PHP_AUTH_USER'] = ''"

.SS "$_SERVER[ 'PHP_SELF'] = ''"

.SS "$_SERVER[ 'QUERY_STRING'] = ''"

.SS "$_SERVER[ 'REMOTE_ADDR'] = ''"

.SS "$_SERVER[ 'REMOTE_HOST'] = ''"

.SS "$_SERVER[ 'REMOTE_PORT'] = ''"

.SS "$_SERVER[ 'REQUEST_METHOD'] = 'GET'"

.SS "$_SERVER[ 'REQUEST_TIME'] = ''"

.SS "$_SERVER[ 'REQUEST_URI'] = '/index\&.html'"

.SS "$_SERVER[ 'SCRIPT_FILENAME'] = ''"

.SS "$_SERVER[ 'SCRIPT_NAME'] = ''"

.SS "$_SERVER[ 'SERVER_ADDR'] = '127\&.0\&.0\&.1'"

.SS "$_SERVER[ 'SERVER_ADMIN'] = ''"

.SS "$_SERVER[ 'SERVER_NAME'] = 'localhost'"

.SS "$_SERVER[ 'SERVER_PORT'] = '80'"

.SS "$_SERVER[ 'SERVER_PROTOCOL'] = 'HTTP/1\&.0'"

.SS "$_SERVER[ 'SERVER_SIGNATURE'] = ''"

.SS "$_SERVER[ 'SERVER_SOFTWARE'] = ''"

.SS "$_SESSION = array()"
@xglobal $_SESSION array @xglobal $HTTP_SESSION_VARS array
.PP
Variables which are currently registered to a script's session\&. Analogous to the old $HTTP_SESSION_VARS array (which is still available, but deprecated)\&. See the Session handling functions section for more information\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$argc = 0"
@xglobal $argc int
.PP
The number of arguments passed to script
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$argv = array()"
@xglobal $argv array
.PP
Array of arguments passed to script
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$GLOBALS = array()"
@xglobal $GLOBALS array Contains a reference to every variable which is currently available within the global scope of the script\&. The keys of this array are the names of the global variables\&. $GLOBALS has existed since PHP 3\&.
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$HTTP_ENV_VARS = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$HTTP_GET_VARS = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$HTTP_POST_FILES = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$HTTP_POST_VARS = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$HTTP_RAW_POST_DATA = ''"
@xglobal $HTTP_RAW_POST_DATA string
.PP
Raw POST data
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP
.PP
\fBDeprecated\fP
.RS 4
5\&.6 Deprecated as of PHP 5\&.6\&.0\&. Use the php://input stream instead\&. 
.RE
.PP

.SS "$http_response_header = array()"
@xglobal $http_response_header array
.PP
HTTP response headers
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SS "$HTTP_SERVER_VARS = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$HTTP_SESSION_VARS = array()"

.PP
\fBDeprecated\fP
.RS 4
4\&.1 
.RE
.PP

.SS "$php_errormsg = ''"
@xglobal $php_errormsg string The previous error message
.PP
\fChttps://secure\&.php\&.net/manual/en/reserved\&.variables\&.php\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
