.TH "src Directory Reference" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBExceptions\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBulkSMS\&.php\fP"
.br
.ti -1c
.RI "file \fBPremiumSMS\&.php\fP"
.br
.ti -1c
.RI "file \fBRequest\&.php\fP"
.br
.ti -1c
.RI "file \fBResponse\&.php\fP"
.br
.ti -1c
.RI "file \fBSDP\&.php\fP"
.br
.ti -1c
.RI "file \fBSubscription\&.php\fP"
.br
.in -1c
