.TH "vendor/apigen/apigen/packages/Reflection/src/Contract/Reflection/Partial/AccessLevelInterface.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Reflection/src/Contract/Reflection/Partial/AccessLevelInterface.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBAccessLevelInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Reflection\\Contract\\Reflection\\Partial\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
