.TH "vendor/roave/better-reflection/test/unit/Fixture/AnonymousClassInstancesOnSameLine.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/AnonymousClassInstancesOnSameLine.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$a\fP = new \fBclass\fP {}"
.br
.ti -1c
.RI "\fB$b\fP = new \fBclass\fP {}"
.br
.ti -1c
.RI "\fBreturn\fP [$\fBa\fP, $\fBb\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBa\fP = new \fBclass\fP {}"

.SS "$\fBb\fP = new \fBclass\fP {}"

.SS "return[ $\fBa\fP, $\fBb\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
