.TH "vendor/roave/better-reflection/test/unit/Fixture/AnonymousClassInstances.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/AnonymousClassInstances.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$a\fP"
.br
.ti -1c
.RI "\fB$b\fP"
.br
.ti -1c
.RI "\fBreturn\fP [$\fBa\fP, $\fBb\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBa\fP"
\fBInitial value:\fP
.PP
.nf
= new class
{
    public function a()
    {

    }
}
.fi
.SS "$\fBb\fP"
\fBInitial value:\fP
.PP
.nf
= new class
{
    public function b()
    {

    }
}
.fi
.SS "return[ $\fBa\fP, $\fBb\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
