.TH "vendor/jetbrains/phpstorm-stubs/apache/apache.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/apache/apache.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBapache_child_terminate\fP ()"
.br
.ti -1c
.RI "\fBapache_get_modules\fP ()"
.br
.ti -1c
.RI "\fBapache_get_version\fP ()"
.br
.ti -1c
.RI "\fBapache_getenv\fP ( $variable, $walk_to_top=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBapache_lookup_uri\fP ( $filename)"
.br
.ti -1c
.RI "\fBapache_note\fP ( $note_name, $note_value='')"
.br
.ti -1c
.RI "\fBapache_request_headers\fP ()"
.br
.ti -1c
.RI "\fBapache_reset_timeout\fP ()"
.br
.ti -1c
.RI "\fBapache_response_headers\fP ()"
.br
.ti -1c
.RI "\fBapache_setenv\fP ( $variable, $value, $walk_to_top=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBgetallheaders\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "apache_child_terminate ()"
Terminate apache process after this request \fBapache_child_terminate()\fP will register the Apache process executing the current PHP request for termination once execution of PHP code is completed\&. It may be used to terminate a process after a script with high memory consumption has been run as memory will usually only be freed internally but not given back to the operating system\&. \fBbool \fBTRUE\fP if PHP is running as an Apache 1 module, the Apache version is non-multithreaded, and the child_terminate PHP directive is enabled (disabled by default)\&. If these conditions are not met, \fBFALSE\fP is returned and an error of level \fBE_WARNING\fP is generated\&.  4\&.0\&.5  5\&.0 \fP
.SS "apache_get_modules ()"
Get a list of loaded Apache modules \fBarray of loaded Apache modules\&.  4\&.3\&.2  5\&.0 \fP
.SS "apache_get_version ()"
Fetch the Apache version \fBstring|false the Apache version on success or \fBFALSE\fP on failure\&.  4\&.3\&.2  5\&.0 \fP
.SS "apache_getenv ( $variable,  $walk_to_top = \fC\fBfalse\fP\fP)"
Get an Apache subprocess_env variable Retrieve an Apache environment variable specified by $variable\&. This function requires Apache 2 otherwise it's undefined\&. \fBstring $variable \fP The Apache environment variable\&. 
.PP
\fBParameters\fP
.RS 4
\fI$walk_to_top\fP 
.RE
.PP
Whether to get the top-level variable available to all Apache layers\&. 
.PP
\fBReturns\fP
.RS 4
string|false The value of the Apache environment variable on success, or \fBFALSE\fP on failure\&. 
.RE
.PP
\fBSince\fP
.RS 4
4\&.3 
.PP
5\&.0 
.RE
.PP

.SS "apache_lookup_uri ( $filename)"
Perform a partial request for the specified URI and return all info about it This performs a partial request for a URI\&. It goes just far enough to obtain all the important information about the given resource\&. This function is supported when PHP is installed as an Apache module or by the NSAPI server module in Netscape/iPlanet/SunONE webservers\&. \fBstring $filename \fP The filename (URI) that's being requested\&. 
.PP
\fBReturns\fP
.RS 4
object of related URI information\&. 
.RE
.PP
\fBSince\fP
.RS 4
4\&.0 
.PP
5\&.0 
.RE
.PP

.SS "apache_note ( $note_name,  $note_value = \fC''\fP)"
Get and set apache request notes This function is a wrapper for Apache's table_get and table_set\&. It edits the table of notes that exists during a request\&. The table's purpose is to allow Apache modules to communicate\&. The main use for \fBapache_note()\fP is to pass information from one module to another within the same request\&. \fBstring $note_name \fP The name of the note\&. 
.PP
\fBParameters\fP
.RS 4
\fI$note_value\fP 
.RE
.PP
The value of the note\&. 
.PP
\fBReturns\fP
.RS 4
string|false If called with one argument, it returns the current value of note note_name\&. If called with two arguments, it sets the value of note note_name to note_value and returns the previous value of note note_name\&. If the note cannot be retrieved, \fBFALSE\fP is returned\&. 
.RE
.PP
\fBSince\fP
.RS 4
4\&.0 
.PP
5\&.0 
.RE
.PP

.SS "apache_request_headers ()"
Fetches all HTTP request headers from the current request \fBarray|false An associative array of all the HTTP headers in the current request, or \fBFALSE</b on failure\&.  4\&.3  5\&.0 \fP\fP
.SS "apache_reset_timeout ()"
Reset the Apache write timer \fBapache_reset_timeout()\fP resets the Apache write timer, which defaults to 300 seconds\&. With set_time_limit(0); ignore_user_abort(true) and periodic \fBapache_reset_timeout()\fP calls, Apache can theoretically run forever\&. This function requires Apache 1\&. \fBbool \fBTRUE\fP on success or \fBFALSE\fP on failure\&.  5\&.1 \fP
.SS "apache_response_headers ()"
Fetch all HTTP response headers \fBarray|false An array of all Apache response headers on success or \fBFALSE\fP on failure\&.  4\&.3  5\&.0 \fP
.SS "apache_setenv ( $variable,  $value,  $walk_to_top = \fC\fBfalse\fP\fP)"
Sets the value of the Apache environment variable specified by variable\&. Note: When setting an Apache environment variable, the corresponding $_SERVER variable is not changed\&. \fBstring $variable \fP The environment variable that's being set\&. 
.PP
\fBParameters\fP
.RS 4
\fI$value\fP 
.RE
.PP
The new variable value\&. 
.PP
\fBParameters\fP
.RS 4
\fI$walk_to_top\fP 
.RE
.PP
Whether to set the top-level variable available to all Apache layers\&. 
.PP
\fBReturns\fP
.RS 4
bool \fBTRUE\fP on success or \fBFALSE\fP on failure\&. 
.RE
.PP
\fBSince\fP
.RS 4
4\&.2 
.PP
5\&.0 
.RE
.PP

.SS "getallheaders ()"
Fetches all HTTP headers from the current request\&. This function is an alias for \fBapache_request_headers()\fP\&. Please read the \fBapache_request_headers()\fP documentation for more information on how this function works\&. \fBarray|false An associative array of all the HTTP headers in the current request, or \fBFALSE\fP on failure\&.  4\&.0  5\&.0 \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
