.TH "vendor/composer/autoload_psr4.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/composer/autoload_psr4.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$vendorDir\fP = \fBdirname\fP(\fBdirname\fP(\fB__FILE__\fP))"
.br
.ti -1c
.RI "\fB$baseDir\fP = \fBdirname\fP($vendorDir)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$baseDir = \fBdirname\fP($vendorDir)"

.SS "$vendorDir = \fBdirname\fP(\fBdirname\fP(\fB__FILE__\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
