.TH "vendor/composer/autoload_real.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/composer/autoload_real.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBComposerAutoloaderInite5cf3f1cd3d89dd66ff3031cf7e58604\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomposerRequiree5cf3f1cd3d89dd66ff3031cf7e58604\fP ($fileIdentifier, $\fBfile\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "composerRequiree5cf3f1cd3d89dd66ff3031cf7e58604 ( $fileIdentifier,  $file)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
