.TH "vendor/symfony/dependency-injection/Tests/Fixtures/config/basic.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/dependency-injection/Tests/Fixtures/config/basic.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSymfony\\Component\\DependencyInjection\\Loader\\Configurator\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBreturn\fP \fBfunction\fP (ContainerConfigurator $\fBc\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
