.TH "vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/1216/bootstrap1216.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/1216/bootstrap1216.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$_ENV\fP ['configAvailableInBootstrap'] = isset($_ENV['loadedFromConfig'])"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$_ENV[ 'configAvailableInBootstrap'] = isset($_ENV['loadedFromConfig'])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
