.TH "vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/1335/bootstrap1335.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/1335/bootstrap1335.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$globalString\fP = 'Hello'"
.br
.ti -1c
.RI "\fB$globalIntTruthy\fP = 1"
.br
.ti -1c
.RI "\fB$globalIntFalsey\fP = 0"
.br
.ti -1c
.RI "\fB$globalFloat\fP = 1\&.123"
.br
.ti -1c
.RI "\fB$globalBoolTrue\fP = \fBtrue\fP"
.br
.ti -1c
.RI "\fB$globalBoolFalse\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fB$globalNull\fP = \fBnull\fP"
.br
.ti -1c
.RI "\fB$globalArray\fP = ['\fBfoo\fP']"
.br
.ti -1c
.RI "\fB$globalNestedArray\fP = [['\fBfoo\fP']]"
.br
.ti -1c
.RI "\fB$globalObject\fP = (object) ['\fBfoo\fP'=> 'bar']"
.br
.ti -1c
.RI "\fB$globalObjectWithBackSlashString\fP = (object) ['\fBfoo\fP'=> 'back\\\\slash']"
.br
.ti -1c
.RI "\fB$globalObjectWithDoubleBackSlashString\fP = (object) ['\fBfoo\fP'=> 'back\\\\\\\\slash']"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$globalArray = ['\fBfoo\fP']"

.SS "$globalBoolFalse = \fBfalse\fP"

.SS "$globalBoolTrue = \fBtrue\fP"

.SS "$globalFloat = 1\&.123"

.SS "$globalIntFalsey = 0"

.SS "$globalIntTruthy = 1"

.SS "$globalNestedArray = [['\fBfoo\fP']]"

.SS "$globalNull = \fBnull\fP"

.SS "$globalObject = (object) ['\fBfoo\fP'=> 'bar']"

.SS "$globalObjectWithBackSlashString = (object) ['\fBfoo\fP'=> 'back\\\\slash']"

.SS "$globalObjectWithDoubleBackSlashString = (object) ['\fBfoo\fP'=> 'back\\\\\\\\slash']"

.SS "$globalString = 'Hello'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
