.TH "vendor/sebastian/object-reflector/tests/_fixture/ChildClass.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/sebastian/object-reflector/tests/_fixture/ChildClass.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBChildClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSebastianBergmann\\ObjectReflector\\TestFixture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
