.TH "vendor/apigen/apigen/packages/Reflection/src/Transformer/BetterReflection/Class_/ClassConstantReflectionTransformer.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Reflection/src/Transformer/BetterReflection/Class_/ClassConstantReflectionTransformer.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassConstantReflectionTransformer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Reflection\\Transformer\\BetterReflection\\Class_\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
