.TH "vendor/phpunit/phpunit/tests/_files/ClassWithNonPublicAttributes.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/_files/ClassWithNonPublicAttributes.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBParentClassWithPrivateAttributes\fP"
.br
.ti -1c
.RI "class \fBParentClassWithProtectedAttributes\fP"
.br
.ti -1c
.RI "class \fBClassWithNonPublicAttributes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
