.TH "vendor/roave/better-reflection/test/unit/Fixture/ClassWithInterfaces.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ClassWithInterfaces.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBA\fP"
.br
.ti -1c
.RI "interface \fBB\fP"
.br
.ti -1c
.RI "class \fBExampleClass\fP"
.br
.ti -1c
.RI "interface \fBC\fP"
.br
.ti -1c
.RI "class \fBSubExampleClass\fP"
.br
.ti -1c
.RI "class \fBSubSubExampleClass\fP"
.br
.ti -1c
.RI "class \fBExampleImplementingCompositeInterface\fP"
.br
.ti -1c
.RI "interface \fBB\fP"
.br
.ti -1c
.RI "interface \fBD\fP"
.br
.ti -1c
.RI "interface \fBA\fP"
.br
.ti -1c
.RI "interface \fBB\fP"
.br
.ti -1c
.RI "interface \fBC\fP"
.br
.ti -1c
.RI "interface \fBD\fP"
.br
.ti -1c
.RI "interface \fBE\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRoave\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\ClassWithInterfaces\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\ClassWithInterfacesOther\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\ClassWithInterfacesExtendingInterfaces\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
