.TH "vendor/apigen/apigen/packages/Annotation/tests/Latte/Filter/AnnotationFilterProviderSource/ClassWithAnnotations.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Annotation/tests/Latte/Filter/AnnotationFilterProviderSource/ClassWithAnnotations.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassWithAnnotations\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Annotation\\Tests\\Latte\\Filter\\AnnotationFilterProviderSource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
