.TH "vendor/roave/better-reflection/test/unit/Fixture/ClassForSourceStubber.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ClassForSourceStubber.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBParentClassForSourceStubber\fP"
.br
.ti -1c
.RI "interface \fBImplementedInterfaceForSourceStubber\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\Fixture\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmethodFromParentTrait\fP ()"
.br
.ti -1c
.RI "\fBmethodFromTrait\fP ()"
.br
.ti -1c
.RI "\fBmethodWithoutVisibility\fP ()"
.br
.ti -1c
.RI "\fBpublicMethod\fP ()"
.br
.ti -1c
.RI "\fBprotectedMethod\fP ()"
.br
.ti -1c
.RI "\fBprivateMethod\fP ()"
.br
.ti -1c
.RI "\fBpublicAbstractMethod\fP ()"
.br
.ti -1c
.RI "\fBpublicFinalMethod\fP ()"
.br
.ti -1c
.RI "\fBmethodWithParameters\fP ($string, $int, $float, $bool, $\fBiterable\fP, $callable)"
.br
.ti -1c
.RI "\fBmethodWithParametersWithTypes\fP (string $string, int $int, float $float, bool $bool, \fBiterable\fP $\fBiterable\fP, callable $callable)"
.br
.ti -1c
.RI "\fBmethodWithParametersWithNullableTypes\fP (?string $string, ?int $int, ?float $float, ?bool $bool, ?\fBiterable\fP $\fBiterable\fP, ?callable $callable)"
.br
.ti -1c
.RI "\fBmethodWithOptionalParameters\fP (string $string='string', int $int=123, float $float=0\&.0, bool $bool=\fBtrue\fP, \fBiterable\fP $\fBiterable\fP=[], ?callable $callable=\fBnull\fP)"
.br
.ti -1c
.RI "\fBmethodWithSelfAndParentParameters\fP (self $self, parent $parent)"
.br
.ti -1c
.RI "\fBmethodWithVariadicParameter\fP (string \&.\&.\&. $variadic)"
.br
.ti -1c
.RI "\fBmethodWithParameterPassedByReference\fP (bool &$bool)"
.br
.ti -1c
.RI "& \fBmethodReturnsReference\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBUsedParentTraitForSourceStubber\fP"
.br
.ti -1c
.RI "trait \fBUsedTraitForSourceStubber\fP"
.br
.ti -1c
.RI "\fB$propertyFromTrait\fP"
.br
.ti -1c
.RI "trait \fBUsedTraitToAliasForSourceStubber\fP"
.br
.ti -1c
.RI "trait \fBSerializable\fP"
.br
.ti -1c
.RI "const \fBCONSTANT_WITHOUT_VISIBILITY\fP = 1"
.br
.ti -1c
.RI "const \fBPUBLIC_CONSTANT\fP = 0\&.0"
.br
.ti -1c
.RI "const \fBPROTECTED_CONSTANT\fP = 'string'"
.br
.ti -1c
.RI "\fB$propertyWithoutVisibility\fP = 0"
.br
.ti -1c
.RI "\fB$protectedProperty\fP = \fBfalse\fP"
.br
.ti -1c
.RI "\fB$publicProperty\fP = 'string'"
.br
.ti -1c
.RI "int \fB$propertyWithTypeHint\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
