.TH "vendor/roave/better-reflection/test/unit/Fixture/ClassesImplementingIterators.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ClassesImplementingIterators.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBTraversable\fP"
.br
.ti -1c
.RI "class \fBTraversableImplementation\fP"
.br
.ti -1c
.RI "class \fBNonTraversableImplementation\fP"
.br
.ti -1c
.RI "class \fBAbstractTraversableImplementation\fP"
.br
.ti -1c
.RI "interface \fBTraversableExtension\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRoave\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\ClassesImplementingIterators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
