.TH "vendor/roave/better-reflection/test/unit/Fixture/ClassWithPropertiesAndTraitProperties.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ClassWithPropertiesAndTraitProperties.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassWithPropertiesAndTraitProperties\fP"
.br
.ti -1c
.RI "class \fBExtendedClassWithPropertiesAndTraitProperties\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBTraitWithProperty\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "trait TraitWithProperty"
\fBInitial value:\fP
.PP
.nf
{
    private $propertyFromTrait
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
