.TH "vendor/roave/better-reflection/test/unit/Fixture/ClassWithConstantsAsDefaultValues.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ClassWithConstantsAsDefaultValues.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBParentClassWithConstant\fP"
.br
.ti -1c
.RI "class \fBClassWithConstantsAsDefaultValues\fP"
.br
.ti -1c
.RI "class \fBOtherClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRoave\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\Fixture\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\FixtureOther\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBTHIS_NAMESPACE_CONST\fP = 'this_namespace'"
.br
.ti -1c
.RI "const \fBOTHER_NAMESPACE_CONST\fP = 'other_namespace'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
