.TH "vendor/phpspec/prophecy/src/Prophecy/Exception/Doubler/ClassCreatorException.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/prophecy/src/Prophecy/Exception/Doubler/ClassCreatorException.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassCreatorException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBProphecy\\Exception\\Doubler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
