.TH "vendor/guzzlehttp/guzzle/src/ClientTrait.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/guzzlehttp/guzzle/src/ClientTrait.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGuzzleHttp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBhead\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBput\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBpost\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBpatch\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBdelete\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBrequestAsync\fP (string $method, $uri, array $options=[])"
.br
.ti -1c
.RI "\fBgetAsync\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBheadAsync\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBputAsync\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBpostAsync\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBpatchAsync\fP ($uri, array $options=[])"
.br
.ti -1c
.RI "\fBdeleteAsync\fP ($uri, array $options=[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBClientTrait\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
