.TH "vendor/phpunit/php-token-stream/tests/_fixture/closure.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-token-stream/tests/_fixture/closure.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$function1\fP = \fBfunction\fP($\fBfoo\fP, $bar) use ($var) {}"
.br
.ti -1c
.RI "\fB$function2\fP = \fBfunction\fP(\fBFoo\fP $\fBfoo\fP, $bar) use ($var) {}"
.br
.ti -1c
.RI "\fB$function3\fP = \fBfunction\fP ($\fBfoo\fP, $bar, $\fBbaz\fP) {}"
.br
.ti -1c
.RI "\fB$function4\fP = \fBfunction\fP (\fBFoo\fP $\fBfoo\fP, $bar, $\fBbaz\fP) {}"
.br
.ti -1c
.RI "\fB$function5\fP = \fBfunction\fP () {}"
.br
.ti -1c
.RI "\fB$function6\fP = \fBfunction\fP() {}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$function1 = \fBfunction\fP($\fBfoo\fP, $bar) use ($var) {}"

.SS "$function2 = \fBfunction\fP(\fBFoo\fP $\fBfoo\fP, $bar) use ($var) {}"

.SS "$function3 = \fBfunction\fP ($\fBfoo\fP, $bar, $\fBbaz\fP) {}"

.SS "$function4 = \fBfunction\fP (\fBFoo\fP $\fBfoo\fP, $bar, $\fBbaz\fP) {}"

.SS "$function5 = \fBfunction\fP () {}"

.SS "$function6 = \fBfunction\fP() {}"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
