.TH "vendor/nette/php-generator/src/PhpGenerator/Traits/CommentAware.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nette/php-generator/src/PhpGenerator/Traits/CommentAware.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNette\\PhpGenerator\\Traits\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetComment\fP (?string $val)"
.br
.ti -1c
.RI "\fBgetComment\fP ()"
.br
.ti -1c
.RI "\fBaddComment\fP (string $val)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBCommentAware\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
