.TH "vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/2158/constant.inc" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/2158/constant.inc
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBTEST_CONSTANT\fP \fBtrue\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const TEST_CONSTANT \fBtrue\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
