.TH "vendor/nette/di/src/Bridges/DITracy/templates/ContainerPanel.tab.phtml" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nette/di/src/Bridges/DITracy/templates/ContainerPanel.tab.phtml
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNette\\Bridges\\DITracy\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
