.TH "vendor/jetbrains/phpstorm-stubs/standard/CSPRNG.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/standard/CSPRNG.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrandom_bytes\fP ($length)"
.br
.ti -1c
.RI "\fBrandom_int\fP ($\fBmin\fP, $\fBmax\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "random_bytes ( $length)"
Generates cryptographically secure pseudo-random bytes \fBint $length The length of the random string that should be returned in bytes\&.  string Returns a string containing the requested number of cryptographically secure random bytes\&.  7\&.0  Exception if it was not possible to gather sufficient entropy\&. \fP
.SS "random_int ( $min,  $max)"
Generates cryptographically secure pseudo-random integers \fBint $min The lowest value to be returned, which must be PHP_INT_MIN or higher\&.  int $max The highest value to be returned, which must be less than or equal to PHP_INT_MAX\&.  int Returns a cryptographically secure random integer in the range min to max, inclusive\&.  7\&.0  Exception if it was not possible to gather sufficient entropy\&. \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
