.TH "vendor/jetbrains/phpstorm-stubs/date/date_c.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/date/date_c.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBDateTimeInterface\fP"
.br
.ti -1c
.RI "class \fBDateTimeImmutable\fP"
.br
.ti -1c
.RI "class \fBDateTime\fP"
.br
.ti -1c
.RI "class \fBDateTimeZone\fP"
.br
.ti -1c
.RI "class \fBDateInterval\fP"
.br
.ti -1c
.RI "class \fBDatePeriod\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
