.TH "vendor/jetbrains/phpstorm-stubs/date/date_d.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/date/date_d.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBDATE_ATOM\fP 'Y\-m\-d\\TH:i:sP'"
.br
.ti -1c
.RI "const \fBDATE_COOKIE\fP 'l, d\-M\-Y H:i:s T'"
.br
.ti -1c
.RI "const \fBDATE_ISO8601\fP 'Y\-m\-d\\TH:i:sO'"
.br
.ti -1c
.RI "const \fBDATE_RFC822\fP 'D, d M y H:i:s \fBO\fP'"
.br
.ti -1c
.RI "const \fBDATE_RFC850\fP 'l, d\-M\-y H:i:s T'"
.br
.ti -1c
.RI "const \fBDATE_RFC1036\fP 'D, d M y H:i:s \fBO\fP'"
.br
.ti -1c
.RI "const \fBDATE_RFC1123\fP 'D, d M Y H:i:s \fBO\fP'"
.br
.ti -1c
.RI "const \fBDATE_RFC2822\fP 'D, d M Y H:i:s \fBO\fP'"
.br
.ti -1c
.RI "const \fBDATE_RFC3339\fP 'Y\-m\-d\\TH:i:sP'"
.br
.ti -1c
.RI "const \fBDATE_RFC3339_EXTENDED\fP 'Y\-m\-d\\TH:i:s\&.vP'"
.br
.ti -1c
.RI "const \fBDATE_RFC7231\fP 'D, d M Y H:i:s \\G\\M\\T'"
.br
.ti -1c
.RI "const \fBDATE_RSS\fP 'D, d M Y H:i:s \fBO\fP'"
.br
.ti -1c
.RI "const \fBDATE_W3C\fP 'Y\-m\-d\\TH:i:sP'"
.br
.ti -1c
.RI "const \fBSUNFUNCS_RET_TIMESTAMP\fP 0"
.br
.ti -1c
.RI "const \fBSUNFUNCS_RET_STRING\fP 1"
.br
.ti -1c
.RI "const \fBSUNFUNCS_RET_DOUBLE\fP 2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const DATE_ATOM 'Y\-m\-d\\TH:i:sP'"

.SS "const DATE_COOKIE 'l, d\-M\-Y H:i:s T'"

.SS "const DATE_ISO8601 'Y\-m\-d\\TH:i:sO'"

.SS "const DATE_RFC1036 'D, d M y H:i:s \fBO\fP'"

.SS "const DATE_RFC1123 'D, d M Y H:i:s \fBO\fP'"

.SS "const DATE_RFC2822 'D, d M Y H:i:s \fBO\fP'"

.SS "const DATE_RFC3339 'Y\-m\-d\\TH:i:sP'"

.SS "const DATE_RFC3339_EXTENDED 'Y\-m\-d\\TH:i:s\&.vP'"

.SS "const DATE_RFC7231 'D, d M Y H:i:s \\G\\M\\T'"

.SS "const DATE_RFC822 'D, d M y H:i:s \fBO\fP'"

.SS "const DATE_RFC850 'l, d\-M\-y H:i:s T'"

.SS "const DATE_RSS 'D, d M Y H:i:s \fBO\fP'"

.SS "const DATE_W3C 'Y\-m\-d\\TH:i:sP'"

.SS "const SUNFUNCS_RET_DOUBLE 2"
Hours as floating point number (example 8\&.75) \fBhttps://php\&.net/manual/en/datetime\&.constants\&.php\fP
.SS "const SUNFUNCS_RET_STRING 1"
Hours:minutes (example: 08:02) \fBhttps://php\&.net/manual/en/datetime\&.constants\&.php\fP
.SS "const SUNFUNCS_RET_TIMESTAMP 0"
Timestamp \fBhttps://php\&.net/manual/en/datetime\&.constants\&.php\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
