.TH "vendor/apigen/apigen/tests/Generator/DeprecatedSources/DeprecatedMethod.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/tests/Generator/DeprecatedSources/DeprecatedMethod.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDeprecatedMethod\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Tests\\Generator\\DeprecatedSources\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
