.TH "vendor/apigen/apigen/packages/Element/tests/ReflectionCollector/Source/deprecatedFunction.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Element/tests/ReflectionCollector/Source/deprecatedFunction.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Element\\Tests\\Annotation\\Annotation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdeprecatedFunction\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
