.TH "vendor/jetbrains/phpstorm-stubs/dom/dom_c.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/dom/dom_c.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDOMNode\fP"
.br
.ti -1c
.RI "class \fBDOMException\fP"
.br
.ti -1c
.RI "class \fBDOMStringList\fP"
.br
.ti -1c
.RI "class \fBDOMNameList\fP"
.br
.ti -1c
.RI "class \fBDOMImplementationList\fP"
.br
.ti -1c
.RI "class \fBDOMImplementationSource\fP"
.br
.ti -1c
.RI "class \fBDOMImplementation\fP"
.br
.ti -1c
.RI "class \fBDOMNameSpaceNode\fP"
.br
.ti -1c
.RI "class \fBDOMDocumentFragment\fP"
.br
.ti -1c
.RI "class \fBDOMDocument\fP"
.br
.ti -1c
.RI "class \fBDOMNodeList\fP"
.br
.ti -1c
.RI "class \fBDOMNamedNodeMap\fP"
.br
.ti -1c
.RI "class \fBDOMCharacterData\fP"
.br
.ti -1c
.RI "class \fBDOMAttr\fP"
.br
.ti -1c
.RI "class \fBDOMElement\fP"
.br
.ti -1c
.RI "class \fBDOMText\fP"
.br
.ti -1c
.RI "class \fBDOMComment\fP"
.br
.ti -1c
.RI "class \fBDOMTypeinfo\fP"
.br
.ti -1c
.RI "class \fBDOMUserDataHandler\fP"
.br
.ti -1c
.RI "class \fBDOMDomError\fP"
.br
.ti -1c
.RI "class \fBDOMErrorHandler\fP"
.br
.ti -1c
.RI "class \fBDOMLocator\fP"
.br
.ti -1c
.RI "class \fBDOMConfiguration\fP"
.br
.ti -1c
.RI "class \fBDOMCdataSection\fP"
.br
.ti -1c
.RI "class \fBDOMDocumentType\fP"
.br
.ti -1c
.RI "class \fBDOMNotation\fP"
.br
.ti -1c
.RI "class \fBDOMEntity\fP"
.br
.ti -1c
.RI "class \fBDOMEntityReference\fP"
.br
.ti -1c
.RI "class \fBDOMProcessingInstruction\fP"
.br
.ti -1c
.RI "class \fBDOMStringExtend\fP"
.br
.ti -1c
.RI "class \fBDOMXPath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
