.TH "vendor/roave/better-reflection/test/unit/Fixture/EvaledAnonymousClassInstance.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/EvaledAnonymousClassInstance.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBreturn\fP \fB$a\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBreturn\fP $\fBa\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
