.TH "vendor/phar-io/manifest/examples/example-01.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phar-io/manifest/examples/example-01.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$manifest\fP = ManifestLoader::fromFile(\fB__DIR__\fP \&. '/\&.\&./tests/_fixture/phpunit\-5\&.6\&.5\&.\fBxml\fP')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$manifest = ManifestLoader::fromFile(\fB__DIR__\fP \&. '/\&.\&./tests/_fixture/phpunit\-5\&.6\&.5\&.\fBxml\fP')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
