.TH "vendor/roave/better-reflection/demo/basic-reflection/example3.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/demo/basic-reflection/example3.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$reflector\fP"
.br
.ti -1c
.RI "\fB$reflection\fP = $reflector\->reflect('\fBMyClass\fP')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$reflection = $reflector\->reflect('\fBMyClass\fP')"

.SS "$reflector"
\fBInitial value:\fP
.PP
.nf
= new ClassReflector(new AggregateSourceLocator([
    new SingleFileSourceLocator(__DIR__ \&. '/assets/MyClass\&.php', (new BetterReflection())->astLocator()),
]))
.fi
\fBExamples\fP
.in +1c
\fB/usr/local/var/www/safaricom\-sdp\-sdk/vendor/roave/better\-reflection/src/SourceLocator/Type/AbstractSourceLocator\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
