.TH "vendor/roave/better-reflection/test/unit/Fixture/ExampleClass.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/ExampleClass.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBExampleClass\fP"
.br
.ti -1c
.RI "class \fBClassWithParent\fP"
.br
.ti -1c
.RI "class \fBClassWithTwoParents\fP"
.br
.ti -1c
.RI "class \fBAbstractClass\fP"
.br
.ti -1c
.RI "class \fBFinalClass\fP"
.br
.ti -1c
.RI "class \fBAnotherClass\fP"
.br
.ti -1c
.RI "class \fBClassWithExplicitGlobalNamespace\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRoave\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\Fixture\fP"
.br
.ti -1c
.RI " \fBRoave\\BetterReflectionTest\\FixtureOther\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
