.TH "vendor/nette/utils/src/Utils/exceptions.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nette/utils/src/Utils/exceptions.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBArgumentOutOfRangeException\fP"
.br
.ti -1c
.RI "class \fBInvalidStateException\fP"
.br
.ti -1c
.RI "class \fBNotImplementedException\fP"
.br
.ti -1c
.RI "class \fBNotSupportedException\fP"
.br
.ti -1c
.RI "class \fBDeprecatedException\fP"
.br
.ti -1c
.RI "class \fBMemberAccessException\fP"
.br
.ti -1c
.RI "class \fBIOException\fP"
.br
.ti -1c
.RI "class \fBFileNotFoundException\fP"
.br
.ti -1c
.RI "class \fBDirectoryNotFoundException\fP"
.br
.ti -1c
.RI "class \fBInvalidArgumentException\fP"
.br
.ti -1c
.RI "class \fBOutOfRangeException\fP"
.br
.ti -1c
.RI "class \fBUnexpectedValueException\fP"
.br
.ti -1c
.RI "class \fBStaticClassException\fP"
.br
.ti -1c
.RI "class \fBImageException\fP"
.br
.ti -1c
.RI "class \fBUnknownImageFileException\fP"
.br
.ti -1c
.RI "class \fBJsonException\fP"
.br
.ti -1c
.RI "class \fBRegexpException\fP"
.br
.ti -1c
.RI "class \fBAssertionException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNette\fP"
.br
.ti -1c
.RI " \fBNette\\Utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
