.TH "vendor/symfony/dependency-injection/Tests/Extension/ExtensionTest.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/dependency-injection/Tests/Extension/ExtensionTest.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBExtensionTest\fP"
.br
.ti -1c
.RI "class \fBEnableableExtension\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSymfony\\Component\\DependencyInjection\\Tests\\Extension\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
