.TH "vendor/jetbrains/phpstorm-stubs/FFI/FFI.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/FFI/FFI.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFFI\fP"
.br
.ti -1c
.RI "class \fBFFI\\Exception\fP"
.br
.ti -1c
.RI "class \fBFFI\\ParserException\fP"
.br
.ti -1c
.RI "class \fBFFI\\CData\fP"
.br
.ti -1c
.RI "class \fBFFI\\CType\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFFI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
