.TH "vendor/roave/better-reflection/test/unit/Fixture/FindReflectionOnLineFixture.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/FindReflectionOnLineFixture.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSomeFooClass\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfooFunc\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBSomeFooTrait\fP"
.br
.ti -1c
.RI "const \fBBOO\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "fooFunc ()"

.SH "Variable Documentation"
.PP 
.SS "const BOO = 1"

.SS "trait SomeFooTrait"
\fBInitial value:\fP
.PP
.nf
{
}

interface SomeFooInterface
{
}

class SomeFooClassWithImplementedInterface implements \\Roave\\BetterReflectionTest\\Fixture\\AutoloadableInterface
{
}

define('FOO', 0)
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
