.TH "vendor/apigen/apigen/packages/Reflection/tests/Reflection/Function_/FunctionParameterReflection/Source/functionWithConstant.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Reflection/tests/Reflection/Function_/FunctionParameterReflection/Source/functionWithConstant.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Reflection\\Tests\\Reflection\\Function_\\FunctionParameterReflection\\Source\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunctionWithConstant\fP (int $hello=HI)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBHI\fP = 5"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
