.TH "vendor/sebastian/resource-operations/build/generate.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/sebastian/resource-operations/build/generate.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$functions\fP = require \fB__DIR__\fP \&. '/\fBarginfo\&.php\fP'"
.br
.ti -1c
.RI "\fB$resourceFunctions\fP = []"
.br
.ti -1c
.RI "\fB$buffer\fP ="
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "foreach ( $resourceFunctions as $\fBfunction\fP) $buffer ="

.SS "$functions = require \fB__DIR__\fP \&. '/\fBarginfo\&.php\fP'"

.SS "foreach ( $functions as $\fBfunction\fP=> $arguments) $resourceFunctions = []"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
