.TH "vendor/jetbrains/phpstorm-stubs/gmagick/gmagick.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/gmagick/gmagick.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBGmagick\fP"
.br
.ti -1c
.RI "class \fBGmagickDraw\fP"
.br
.ti -1c
.RI "class \fBGmagickException\fP"
.br
.ti -1c
.RI "class \fBGmagickPixel\fP"
.br
.ti -1c
.RI "class \fBGmagickPixelException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
