.TH "vendor/jetbrains/phpstorm-stubs/gnupg/gnupg.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/gnupg/gnupg.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBgnupg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBGNUPG_SIG_MODE_NORMAL\fP 0"
.br
.ti -1c
.RI "const \fBGNUPG_SIG_MODE_DETACH\fP 1"
.br
.ti -1c
.RI "const \fBGNUPG_SIG_MODE_CLEAR\fP 2"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_UNKNOWN\fP 0"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_UNDEFINED\fP 1"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_NEVER\fP 2"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_MARGINAL\fP 3"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_FULL\fP 4"
.br
.ti -1c
.RI "const \fBGNUPG_VALIDITY_ULTIMATE\fP 5"
.br
.ti -1c
.RI "const \fBGNUPG_PROTOCOL_OpenPGP\fP 0"
.br
.ti -1c
.RI "const \fBGNUPG_PROTOCOL_CMS\fP 1"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_VALID\fP 1"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_GREEN\fP 2"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_RED\fP 4"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_KEY_REVOKED\fP 16"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_KEY_EXPIRED\fP 32"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_SIG_EXPIRED\fP 64"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_KEY_MISSING\fP 128"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_CRL_MISSING\fP 256"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_CRL_TOO_OLD\fP 512"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_BAD_POLICY\fP 1024"
.br
.ti -1c
.RI "const \fBGNUPG_SIGSUM_SYS_ERROR\fP 2048"
.br
.ti -1c
.RI "const \fBGNUPG_ERROR_WARNING\fP 1"
.br
.ti -1c
.RI "const \fBGNUPG_ERROR_EXCEPTION\fP 2"
.br
.ti -1c
.RI "const \fBGNUPG_ERROR_SILENT\fP 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const GNUPG_ERROR_EXCEPTION 2"

.SS "const GNUPG_ERROR_SILENT 3"

.SS "const GNUPG_ERROR_WARNING 1"

.SS "const GNUPG_PROTOCOL_CMS 1"

.SS "const GNUPG_PROTOCOL_OpenPGP 0"

.SS "const GNUPG_SIG_MODE_CLEAR 2"

.SS "const GNUPG_SIG_MODE_DETACH 1"

.SS "const GNUPG_SIG_MODE_NORMAL 0"
GNUPG Constants \fBhttps://php\&.net/manual/en/gnupg\&.constants\&.php\fP
.SS "const GNUPG_SIGSUM_BAD_POLICY 1024"

.SS "const GNUPG_SIGSUM_CRL_MISSING 256"

.SS "const GNUPG_SIGSUM_CRL_TOO_OLD 512"

.SS "const GNUPG_SIGSUM_GREEN 2"

.SS "const GNUPG_SIGSUM_KEY_EXPIRED 32"

.SS "const GNUPG_SIGSUM_KEY_MISSING 128"

.SS "const GNUPG_SIGSUM_KEY_REVOKED 16"

.SS "const GNUPG_SIGSUM_RED 4"

.SS "const GNUPG_SIGSUM_SIG_EXPIRED 64"

.SS "const GNUPG_SIGSUM_SYS_ERROR 2048"

.SS "const GNUPG_SIGSUM_VALID 1"

.SS "const GNUPG_VALIDITY_FULL 4"

.SS "const GNUPG_VALIDITY_MARGINAL 3"

.SS "const GNUPG_VALIDITY_NEVER 2"

.SS "const GNUPG_VALIDITY_ULTIMATE 5"

.SS "const GNUPG_VALIDITY_UNDEFINED 1"

.SS "const GNUPG_VALIDITY_UNKNOWN 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
