.TH "vendor/jetbrains/phpstorm-stubs/imagick/imagick.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/imagick/imagick.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBImagickException\fP"
.br
.ti -1c
.RI "class \fBImagickDrawException\fP"
.br
.ti -1c
.RI "class \fBImagickPixelIteratorException\fP"
.br
.ti -1c
.RI "class \fBImagickPixelException\fP"
.br
.ti -1c
.RI "class \fBImagick\fP"
.br
.ti -1c
.RI "class \fBImagickDraw\fP"
.br
.ti -1c
.RI "class \fBImagickPixelIterator\fP"
.br
.ti -1c
.RI "class \fBImagickPixel\fP"
.br
.ti -1c
.RI "class \fBImagickKernel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
