.TH "vendor/roave/better-reflection/test/unit/Fixture/InheritedClassProperties.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/InheritedClassProperties.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBaz\fP"
.br
.ti -1c
.RI "class \fBQux\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBBar\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "trait \fBBar\fP"
\fBInitial value:\fP
.PP
.nf
{
    public $a
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
