.TH "vendor/roave/better-reflection/test/unit/Fixture/InheritedClassConstants.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/InheritedClassConstants.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBFoo\fP"
.br
.ti -1c
.RI "interface \fBBoo\fP"
.br
.ti -1c
.RI "class \fBBaz\fP"
.br
.ti -1c
.RI "class \fBQux\fP"
.br
.ti -1c
.RI "class \fBNext\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
