.TH "vendor/phpunit/phpunit/tests/end-to-end/regression/Trac/523/Issue523Test.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/end-to-end/regression/Trac/523/Issue523Test.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIssue523Test\fP"
.br
.ti -1c
.RI "class \fBIssue523\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
