.TH "vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/873/Issue873Test.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/end-to-end/regression/GitHub/873/Issue873Test.php
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
