.TH "vendor/jetbrains/phpstorm-stubs/leveldb/LevelDB.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/leveldb/LevelDB.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLevelDB\fP"
.br
.ti -1c
.RI "class \fBLevelDBIterator\fP"
.br
.ti -1c
.RI "class \fBLevelDBWriteBatch\fP"
.br
.ti -1c
.RI "class \fBLevelDBSnapshot\fP"
.br
.ti -1c
.RI "class \fBLevelDBException\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBLEVELDB_NO_COMPRESSION\fP 0"
.br
.ti -1c
.RI "const \fBLEVELDB_SNAPPY_COMPRESSION\fP 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const LEVELDB_NO_COMPRESSION 0"

.SS "const LEVELDB_SNAPPY_COMPRESSION 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
