.TH "tests/LoadEnv.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/LoadEnv.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhelix\\SafaricomSDP\\Tests\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$_ENV\fP ['SFC_SDP_API_USERNAME'] = 'CosmereAPI'"
.br
.ti -1c
.RI "\fB$_ENV\fP ['SFC_SDP_API_PASSWORD'] = '#K4k4m3ga20192'"
.br
.ti -1c
.RI "\fB$_ENV\fP ['SFC_SDP_CP_ID'] = 23"
.br
.ti -1c
.RI "\fB$_ENV\fP ['SFC_SDP_DEBUG'] = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
