.TH "vendor/psr/log/Psr/Log/LoggerAwareTrait.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/psr/log/Psr/Log/LoggerAwareTrait.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPsr\\Log\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetLogger\fP (LoggerInterface $logger)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBLoggerAwareTrait\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
