.TH "vendor/guzzlehttp/psr7/src/MessageTrait.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/guzzlehttp/psr7/src/MessageTrait.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGuzzleHttp\\Psr7\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetProtocolVersion\fP ()"
.br
.ti -1c
.RI "\fBwithProtocolVersion\fP ($\fBversion\fP)"
.br
.ti -1c
.RI "\fBgetHeaders\fP ()"
.br
.ti -1c
.RI "\fBhasHeader\fP ($\fBheader\fP)"
.br
.ti -1c
.RI "\fBgetHeader\fP ($\fBheader\fP)"
.br
.ti -1c
.RI "\fBgetHeaderLine\fP ($\fBheader\fP)"
.br
.ti -1c
.RI "\fBwithHeader\fP ($\fBheader\fP, $value)"
.br
.ti -1c
.RI "\fBwithAddedHeader\fP ($\fBheader\fP, $value)"
.br
.ti -1c
.RI "\fBwithoutHeader\fP ($\fBheader\fP)"
.br
.ti -1c
.RI "\fBgetBody\fP ()"
.br
.ti -1c
.RI "\fBwithBody\fP (StreamInterface $body)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBMessageTrait\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
