.TH "vendor/jetbrains/phpstorm-stubs/ming/ming.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/ming/ming.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSWFShape\fP"
.br
.ti -1c
.RI "class \fBSWFFill\fP"
.br
.ti -1c
.RI "class \fBSWFGradient\fP"
.br
.ti -1c
.RI "class \fBSWFBitmap\fP"
.br
.ti -1c
.RI "class \fBSWFText\fP"
.br
.ti -1c
.RI "class \fBSWFTextField\fP"
.br
.ti -1c
.RI "class \fBSWFFont\fP"
.br
.ti -1c
.RI "class \fBSWFDisplayItem\fP"
.br
.ti -1c
.RI "class \fBSWFMovie\fP"
.br
.ti -1c
.RI "class \fBSWFButton\fP"
.br
.ti -1c
.RI "class \fBSWFAction\fP"
.br
.ti -1c
.RI "class \fBSWFMorph\fP"
.br
.ti -1c
.RI "class \fBSWFSprite\fP"
.br
.ti -1c
.RI "class \fBSWFSound\fP"
.br
.ti -1c
.RI "class \fBSWFFontChar\fP"
.br
.ti -1c
.RI "class \fBSWFSoundInstance\fP"
.br
.ti -1c
.RI "class \fBSWFVideoStream\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBming_setcubicthreshold\fP ($threshold)"
.br
.ti -1c
.RI "\fBming_setscale\fP ($scale)"
.br
.ti -1c
.RI "\fBming_useswfversion\fP ($\fBversion\fP)"
.br
.ti -1c
.RI "\fBming_keypress\fP ($char)"
.br
.ti -1c
.RI "\fBming_useconstants\fP ($use)"
.br
.ti -1c
.RI "\fBming_setswfcompression\fP ($level)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBMING_NEW\fP 1"
.br
.ti -1c
.RI "const \fBMING_ZLIB\fP 1"
.br
.ti -1c
.RI "const \fBSWFBUTTON_HIT\fP 8"
.br
.ti -1c
.RI "const \fBSWFBUTTON_DOWN\fP 4"
.br
.ti -1c
.RI "const \fBSWFBUTTON_OVER\fP 2"
.br
.ti -1c
.RI "const \fBSWFBUTTON_UP\fP 1"
.br
.ti -1c
.RI "const \fBSWFBUTTON_MOUSEUPOUTSIDE\fP 64"
.br
.ti -1c
.RI "const \fBSWFBUTTON_DRAGOVER\fP 160"
.br
.ti -1c
.RI "const \fBSWFBUTTON_DRAGOUT\fP 272"
.br
.ti -1c
.RI "const \fBSWFBUTTON_MOUSEUP\fP 8"
.br
.ti -1c
.RI "const \fBSWFBUTTON_MOUSEDOWN\fP 4"
.br
.ti -1c
.RI "const \fBSWFBUTTON_MOUSEOUT\fP 2"
.br
.ti -1c
.RI "const \fBSWFBUTTON_MOUSEOVER\fP 1"
.br
.ti -1c
.RI "const \fBSWFFILL_RADIAL_GRADIENT\fP 18"
.br
.ti -1c
.RI "const \fBSWFFILL_LINEAR_GRADIENT\fP 16"
.br
.ti -1c
.RI "const \fBSWFFILL_TILED_BITMAP\fP 64"
.br
.ti -1c
.RI "const \fBSWFFILL_CLIPPED_BITMAP\fP 65"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_HASLENGTH\fP 2"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_NOEDIT\fP 8"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_PASSWORD\fP 16"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_MULTILINE\fP 32"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_WORDWRAP\fP 64"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_DRAWBOX\fP 2048"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_NOSELECT\fP 4096"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_HTML\fP 512"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_USEFONT\fP 256"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_AUTOSIZE\fP 16384"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_ALIGN_LEFT\fP 0"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_ALIGN_RIGHT\fP 1"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_ALIGN_CENTER\fP 2"
.br
.ti -1c
.RI "const \fBSWFTEXTFIELD_ALIGN_JUSTIFY\fP 3"
.br
.ti -1c
.RI "const \fBSWFACTION_ONLOAD\fP 1"
.br
.ti -1c
.RI "const \fBSWFACTION_ENTERFRAME\fP 2"
.br
.ti -1c
.RI "const \fBSWFACTION_UNLOAD\fP 4"
.br
.ti -1c
.RI "const \fBSWFACTION_MOUSEMOVE\fP 8"
.br
.ti -1c
.RI "const \fBSWFACTION_MOUSEDOWN\fP 16"
.br
.ti -1c
.RI "const \fBSWFACTION_MOUSEUP\fP 32"
.br
.ti -1c
.RI "const \fBSWFACTION_KEYDOWN\fP 64"
.br
.ti -1c
.RI "const \fBSWFACTION_KEYUP\fP 128"
.br
.ti -1c
.RI "const \fBSWFACTION_DATA\fP 256"
.br
.ti -1c
.RI "const \fBSWF_SOUND_NOT_COMPRESSED\fP 0"
.br
.ti -1c
.RI "const \fBSWF_SOUND_ADPCM_COMPRESSED\fP 16"
.br
.ti -1c
.RI "const \fBSWF_SOUND_MP3_COMPRESSED\fP 32"
.br
.ti -1c
.RI "const \fBSWF_SOUND_NOT_COMPRESSED_LE\fP 48"
.br
.ti -1c
.RI "const \fBSWF_SOUND_NELLY_COMPRESSED\fP 96"
.br
.ti -1c
.RI "const \fBSWF_SOUND_5KHZ\fP 0"
.br
.ti -1c
.RI "const \fBSWF_SOUND_11KHZ\fP 4"
.br
.ti -1c
.RI "const \fBSWF_SOUND_22KHZ\fP 8"
.br
.ti -1c
.RI "const \fBSWF_SOUND_44KHZ\fP 12"
.br
.ti -1c
.RI "const \fBSWF_SOUND_8BITS\fP 0"
.br
.ti -1c
.RI "const \fBSWF_SOUND_16BITS\fP 2"
.br
.ti -1c
.RI "const \fBSWF_SOUND_MONO\fP 0"
.br
.ti -1c
.RI "const \fBSWF_SOUND_STEREO\fP 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ming_keypress ( $char)"
Returns the action flag for keyPress(char) \fB$char string  int What the function returns, first on success, then on failure\&. See also the &return\&.success; entity \fP
.SS "ming_setcubicthreshold ( $threshold)"
Set cubic threshold \fB$threshold int \fP The Threshold\&. Lower is more accurate, hence larger file size\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "ming_setscale ( $scale)"
Set the global scaling factor\&. \fB$scale int \fP The scale to be set\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "ming_setswfcompression ( $level)"
Sets the SWF output compression \fB$level int \fP The new compression level\&. Should be a value between 1 and 9 inclusive\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "ming_useconstants ( $use)"
Use constant pool \fB$use int \fP Its description 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "ming_useswfversion ( $version)"
Sets the SWF version \fB$version int \fP SWF version to use\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const MING_NEW 1"

.SS "const MING_ZLIB 1"

.SS "const SWF_SOUND_11KHZ 4"

.SS "const SWF_SOUND_16BITS 2"

.SS "const SWF_SOUND_22KHZ 8"

.SS "const SWF_SOUND_44KHZ 12"

.SS "const SWF_SOUND_5KHZ 0"

.SS "const SWF_SOUND_8BITS 0"

.SS "const SWF_SOUND_ADPCM_COMPRESSED 16"

.SS "const SWF_SOUND_MONO 0"

.SS "const SWF_SOUND_MP3_COMPRESSED 32"

.SS "const SWF_SOUND_NELLY_COMPRESSED 96"

.SS "const SWF_SOUND_NOT_COMPRESSED 0"

.SS "const SWF_SOUND_NOT_COMPRESSED_LE 48"

.SS "const SWF_SOUND_STEREO 1"

.SS "const SWFACTION_DATA 256"

.SS "const SWFACTION_ENTERFRAME 2"

.SS "const SWFACTION_KEYDOWN 64"

.SS "const SWFACTION_KEYUP 128"

.SS "const SWFACTION_MOUSEDOWN 16"

.SS "const SWFACTION_MOUSEMOVE 8"

.SS "const SWFACTION_MOUSEUP 32"

.SS "const SWFACTION_ONLOAD 1"

.SS "const SWFACTION_UNLOAD 4"

.SS "const SWFBUTTON_DOWN 4"

.SS "const SWFBUTTON_DRAGOUT 272"

.SS "const SWFBUTTON_DRAGOVER 160"

.SS "const SWFBUTTON_HIT 8"

.SS "const SWFBUTTON_MOUSEDOWN 4"

.SS "const SWFBUTTON_MOUSEOUT 2"

.SS "const SWFBUTTON_MOUSEOVER 1"

.SS "const SWFBUTTON_MOUSEUP 8"

.SS "const SWFBUTTON_MOUSEUPOUTSIDE 64"

.SS "const SWFBUTTON_OVER 2"

.SS "const SWFBUTTON_UP 1"

.SS "const SWFFILL_CLIPPED_BITMAP 65"

.SS "const SWFFILL_LINEAR_GRADIENT 16"

.SS "const SWFFILL_RADIAL_GRADIENT 18"

.SS "const SWFFILL_TILED_BITMAP 64"

.SS "const SWFTEXTFIELD_ALIGN_CENTER 2"

.SS "const SWFTEXTFIELD_ALIGN_JUSTIFY 3"

.SS "const SWFTEXTFIELD_ALIGN_LEFT 0"

.SS "const SWFTEXTFIELD_ALIGN_RIGHT 1"

.SS "const SWFTEXTFIELD_AUTOSIZE 16384"

.SS "const SWFTEXTFIELD_DRAWBOX 2048"

.SS "const SWFTEXTFIELD_HASLENGTH 2"

.SS "const SWFTEXTFIELD_HTML 512"

.SS "const SWFTEXTFIELD_MULTILINE 32"

.SS "const SWFTEXTFIELD_NOEDIT 8"

.SS "const SWFTEXTFIELD_NOSELECT 4096"

.SS "const SWFTEXTFIELD_PASSWORD 16"

.SS "const SWFTEXTFIELD_USEFONT 256"

.SS "const SWFTEXTFIELD_WORDWRAP 64"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
