.TH "vendor/jetbrains/phpstorm-stubs/mongodb/mongodb.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/mongodb/mongodb.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBManager\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.ti -1c
.RI "class \fBQuery\fP"
.br
.ti -1c
.RI "class \fBCommand\fP"
.br
.ti -1c
.RI "class \fBReadPreference\fP"
.br
.ti -1c
.RI "class \fBReadConcern\fP"
.br
.ti -1c
.RI "class \fBCursor\fP"
.br
.ti -1c
.RI "class \fBCursorId\fP"
.br
.ti -1c
.RI "class \fBBulkWrite\fP"
.br
.ti -1c
.RI "class \fBWriteConcern\fP"
.br
.ti -1c
.RI "class \fBWriteResult\fP"
.br
.ti -1c
.RI "class \fBWriteError\fP"
.br
.ti -1c
.RI "class \fBWriteConcernError\fP"
.br
.ti -1c
.RI "class \fBSession\fP"
.br
.ti -1c
.RI "interface \fBCursorInterface\fP"
.br
.ti -1c
.RI "class \fBRuntimeException\fP"
.br
.ti -1c
.RI "interface \fBException\fP"
.br
.ti -1c
.RI "class \fBAuthenticationException\fP"
.br
.ti -1c
.RI "class \fBConnectionException\fP"
.br
.ti -1c
.RI "class \fBInvalidArgumentException\fP"
.br
.ti -1c
.RI "class \fBCommandException\fP"
.br
.ti -1c
.RI "class \fBServerException\fP"
.br
.ti -1c
.RI "class \fBWriteException\fP"
.br
.ti -1c
.RI "class \fBWriteConcernException\fP"
.br
.ti -1c
.RI "class \fBUnexpectedValueException\fP"
.br
.ti -1c
.RI "class \fBBulkWriteException\fP"
.br
.ti -1c
.RI "class \fBConnectionTimeoutException\fP"
.br
.ti -1c
.RI "class \fBExecutionTimeoutException\fP"
.br
.ti -1c
.RI "class \fBLogicException\fP"
.br
.ti -1c
.RI "class \fBSSLConnectionException\fP"
.br
.ti -1c
.RI "interface \fBSubscriber\fP"
.br
.ti -1c
.RI "interface \fBCommandSubscriber\fP"
.br
.ti -1c
.RI "class \fBCommandSucceededEvent\fP"
.br
.ti -1c
.RI "class \fBCommandFailedEvent\fP"
.br
.ti -1c
.RI "class \fBCommandStartedEvent\fP"
.br
.ti -1c
.RI "class \fBBinary\fP"
.br
.ti -1c
.RI "class \fBDecimal128\fP"
.br
.ti -1c
.RI "class \fBJavascript\fP"
.br
.ti -1c
.RI "class \fBMaxKey\fP"
.br
.ti -1c
.RI "class \fBMinKey\fP"
.br
.ti -1c
.RI "class \fBObjectId\fP"
.br
.ti -1c
.RI "class \fBRegex\fP"
.br
.ti -1c
.RI "class \fBTimestamp\fP"
.br
.ti -1c
.RI "class \fBUTCDateTime\fP"
.br
.ti -1c
.RI "class \fBUndefined\fP"
.br
.ti -1c
.RI "class \fBSymbol\fP"
.br
.ti -1c
.RI "class \fBDbPointer\fP"
.br
.ti -1c
.RI "class \fBInt64\fP"
.br
.ti -1c
.RI "interface \fBBinaryInterface\fP"
.br
.ti -1c
.RI "interface \fBObjectIdInterface\fP"
.br
.ti -1c
.RI "interface \fBRegexInterface\fP"
.br
.ti -1c
.RI "interface \fBUTCDateTimeInterface\fP"
.br
.ti -1c
.RI "interface \fBMaxKeyInterface\fP"
.br
.ti -1c
.RI "interface \fBMinKeyInterface\fP"
.br
.ti -1c
.RI "interface \fBDecimal128Interface\fP"
.br
.ti -1c
.RI "interface \fBPersistable\fP"
.br
.ti -1c
.RI "interface \fBSerializable\fP"
.br
.ti -1c
.RI "interface \fBUnserializable\fP"
.br
.ti -1c
.RI "interface \fBType\fP"
.br
.ti -1c
.RI "interface \fBTimestampInterface\fP"
.br
.ti -1c
.RI "interface \fBJavascriptInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMongoDB\fP"
.br
.ti -1c
.RI " \fBMongoDB\\Driver\fP"
.br
.ti -1c
.RI " \fBMongoDB\\Driver\\Exception\fP"
.br
.ti -1c
.RI " \fBMongoDB\\Driver\\Monitoring\fP"
.br
.ti -1c
.RI " \fBMongoDB\\BSON\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaddSubscriber\fP (Subscriber $subscriber)"
.br
.ti -1c
.RI "\fBremoveSubscriber\fP (Subscriber $subscriber)"
.br
.ti -1c
.RI "\fBtoCanonicalExtendedJSON\fP ($bson)"
.br
.ti -1c
.RI "\fBtoRelaxedExtendedJSON\fP ($bson)"
.br
.ti -1c
.RI "\fBfromJSON\fP ($\fBjson\fP)"
.br
.ti -1c
.RI "\fBfromPHP\fP ($value)"
.br
.ti -1c
.RI "\fBtoJSON\fP ($bson)"
.br
.ti -1c
.RI "\fBtoPHP\fP ($bson, array $typeMap)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
