.TH "vendor/jetbrains/phpstorm-stubs/msgpack/msgpack.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/msgpack/msgpack.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMessagePack\fP"
.br
.ti -1c
.RI "class \fBMessagePackUnpacker\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmsgpack_serialize\fP ($value)"
.br
.ti -1c
.RI "\fBmsgpack_unserialize\fP ($str, $object=NULL)"
.br
.ti -1c
.RI "\fBmsgpack_pack\fP ($value)"
.br
.ti -1c
.RI "\fBmsgpack_unpack\fP ($str, $object=\fBnull\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBMESSAGEPACK_OPT_PHPONLY\fP = \-1001"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "msgpack_pack ( $value)"
Alias of msgpack_serialize 
.PP
\fBParameters\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP
\fBSince\fP
.RS 4
5\&.0 
.RE
.PP

.SS "msgpack_serialize ( $value)"
Serialize a variable into msgpack format 
.PP
\fBParameters\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns\fP
.RS 4
string 
.RE
.PP
\fBSince\fP
.RS 4
5\&.0 
.RE
.PP

.SS "msgpack_unpack ( $str,  $object = \fC\fBnull\fP\fP)"
Alias of msgpack_unserialize 
.PP
\fBParameters\fP
.RS 4
\fI$str\fP 
.br
\fI$object\fP 
.RE
.PP
Undocumented template parameter 
.PP
\fBReturns\fP
.RS 4
mixed 
.RE
.PP
\fBSince\fP
.RS 4
5\&.0 
.RE
.PP

.SS "msgpack_unserialize ( $str,  $object = \fCNULL\fP)"
Unserialize $str 
.PP
\fBParameters\fP
.RS 4
\fI$str\fP 
.br
\fI$object\fP 
.RE
.PP
Undocumented template parameter 
.PP
\fBReturns\fP
.RS 4
mixed 
.RE
.PP
\fBSince\fP
.RS 4
5\&.0 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const MESSAGEPACK_OPT_PHPONLY = \-1001"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
