.TH "vendor/phpunit/phpunit/tests/_files/NamespaceCoveredFunction.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/_files/NamespaceCoveredFunction.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBfoo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunc\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
