.TH "vendor/jetbrains/phpstorm-stubs/parallel/parallel.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/parallel/parallel.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBparallel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbootstrap\fP (string $\fBfile\fP)"
.br
.ti -1c
.RI "\fBrun\fP (\fBClosure\fP $task, array $argv=\fBnull\fP)"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
