.TH "vendor/symfony/dependency-injection/Loader/Configurator/Traits/ParentTrait.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/dependency-injection/Loader/Configurator/Traits/ParentTrait.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSymfony\\Component\\DependencyInjection\\Loader\\Configurator\\Traits\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
