.TH "vendor/sebastian/diff/tests/fixtures/patch.txt" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/sebastian/diff/tests/fixtures/patch.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "diff git \fBa\fP \fBFoo\fP php \fBb\fP \fBFoo\fP php index abcdefg abcdefh \fBa\fP \fBFoo\fP php \fBb\fP \fBFoo\fP \fBphp\fP"
.br
.ti -1c
.RI "diff git \fBa\fP \fBFoo\fP \fBphp\fP \fBb\fP \fBFoo\fP \fBphp\fP index abcdefg abcdefh \fBa\fP \fBFoo\fP \fBphp\fP \fBb\fP \fBFoo\fP \fBclass\fP \fBFoo\fP const \fBONE\fP = 1"
.br
.ti -1c
.RI "const \fBTWO\fP = 2"
.br
.ti -1c
.RI "const \fBTHREE\fP = 3"
.br
.ti -1c
.RI "const \fBFOUR\fP = 4"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const FOUR = 4"

.SS "diff git \fBa\fP \fBFoo\fP \fBphp\fP \fBb\fP \fBFoo\fP \fBphp\fP index abcdefg abcdefh \fBa\fP \fBFoo\fP \fBphp\fP \fBb\fP \fBFoo\fP \fBclass\fP \fBFoo\fP const ONE = 1"

.SS "diff git \fBa\fP \fBFoo\fP php \fBb\fP \fBFoo\fP php index abcdefg abcdefh \fBa\fP \fBFoo\fP php \fBb\fP \fBFoo\fP php"

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/var/www/safaricom\-sdp\-sdk/vendor/jetbrains/phpstorm\-stubs/redis/Redis\&.php\fP, \fB/usr/local/var/www/safaricom\-sdp\-sdk/vendor/jetbrains/phpstorm\-stubs/redis/RedisCluster\&.php\fP, \fB/usr/local/var/www/safaricom\-sdp\-sdk/vendor/roave/better\-reflection/src/Reflection/ReflectionClass\&.php\fP, and \fB/usr/local/var/www/safaricom\-sdp\-sdk/vendor/roave/better\-reflection/src/SourceLocator/Type/AbstractSourceLocator\&.php\fP\&.
.SS "const THREE = 3"

.SS "const TWO = 2"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
