.TH "vendor/jetbrains/phpstorm-stubs/pdo_ibm/pdo_ibm.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/pdo_ibm/pdo_ibm.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconfirm_pdo_ibm_compiled\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "confirm_pdo_ibm_compiled ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
