.TH "vendor/jetbrains/phpstorm-stubs/pdo_sqlite/pdo_sqlite.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/pdo_sqlite/pdo_sqlite.php
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
