.TH "Phelix\SafaricomSDP" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Phelix\SafaricomSDP
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBExceptions\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBulkSMS\fP"
.br
.ti -1c
.RI "class \fBPremiumSMS\fP"
.br
.ti -1c
.RI "class \fBRequest\fP"
.br
.ti -1c
.RI "class \fBResponse\fP"
.br
.ti -1c
.RI "class \fBSDP\fP"
.br
.ti -1c
.RI "class \fBSubscription\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
