.TH "Utils" 3 "Sat Sep 26 2020" "Safaricom SDP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetResponse\fP (\fBRequest\fP $response)"
.br
.ti -1c
.RI "static \fBgetCallback\fP ()"
.br
.ti -1c
.RI "static \fBgetCallbackResponseDataItemValue\fP ($responseData, $item)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static getCallback ()\fC [static]\fP"
Get callback data 
.SS "static getCallbackResponseDataItemValue ( $responseData,  $item)\fC [static]\fP"
Get \fBSDP\fP callback data from an array 
.PP
\fBParameters\fP
.RS 4
\fI$responseData\fP 
.br
\fI$item\fP 
.RE
.PP
\fBReturns\fP
.RS 4
mixed|string 
.RE
.PP

.SS "static getResponse (\fBRequest\fP $response)\fC [static]\fP"
Get response
.PP
\fBParameters\fP
.RS 4
\fI$response\fP 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP SDK from the source code\&.
