.TH "Request" 3 "Sat Sep 26 2020" "Safaricom SDP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Request
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($baseURI)"
.br
.ti -1c
.RI "\fBrequest\fP ($method, $uri, $token=null, $body=null, $query_params=null)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$client\fP"
.br
.ti -1c
.RI "\fB$success\fP = true"
.br
.ti -1c
.RI "\fB$statusCode\fP"
.br
.ti -1c
.RI "\fB$statusText\fP"
.br
.ti -1c
.RI "\fB$responseBody\fP"
.br
.ti -1c
.RI "\fB$errorCode\fP"
.br
.ti -1c
.RI "\fB$errorMessage\fP"
.br
.ti -1c
.RI "\fB$debugRequestTrace\fP"
.br
.ti -1c
.RI "\fB$debugResponseTrace\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $baseURI)"
\fBRequest\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$baseURI\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "request ( $method,  $uri,  $token = \fCnull\fP,  $body = \fCnull\fP,  $query_params = \fCnull\fP)"
Make a http request
.PP
\fBParameters\fP
.RS 4
\fI$method\fP 
.br
\fI$uri\fP 
.br
\fI$token\fP 
.br
\fI$body\fP 
.br
\fI$query_params\fP 
.RE
.PP
\fBReturns\fP
.RS 4
$this 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "$client"

.SS "$debugRequestTrace"

.SS "$debugResponseTrace"

.SS "$errorCode"

.SS "$errorMessage"

.SS "$responseBody"

.SS "$statusCode"

.SS "$statusText"

.SS "$success = true"


.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP SDK from the source code\&.
