.TH "SDPException" 3 "Sat Sep 26 2020" "Safaricom SDP SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDPException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $code=0, Exception $previous=null)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $code = \fC0\fP, Exception $previous = \fCnull\fP)"
Redefine the exception so message isn't optional \fBSDPException\fP constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fI$message\fP 
.br
\fI$code\fP 
.br
\fI$previous\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP SDK from the source code\&.
