.TH "Response" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetResponse\fP (\fBRequest\fP $response)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static getResponse (\fBRequest\fP $response)\fC [static]\fP"
Get response
.PP
\fBParameters\fP
.RS 4
\fI$response\fP 
.RE
.PP
\fBReturns\fP
.RS 4
array 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
