.TH "vendor/roave/better-reflection/test/unit/Fixture/Php7ReturnTypeDeclarations.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/Php7ReturnTypeDeclarations.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBreturnsInt\fP ()"
.br
.ti -1c
.RI "\fBreturnsString\fP ()"
.br
.ti -1c
.RI "\fBreturnsObject\fP ()"
.br
.ti -1c
.RI "\fBreturnsNull\fP ()"
.br
.ti -1c
.RI "\fBreturnsNothing\fP ()"
.br
.ti -1c
.RI "\fBreturnsVoid\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "returnsInt ()"

.SS "returnsNothing ()"

.SS "returnsNull ()"

.SS "returnsObject ()"

.SS "returnsString ()"

.SS "returnsVoid ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
