.TH "vendor/jetbrains/phpstorm-stubs/tests/Model/PHPDocElement.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/tests/Model/PHPDocElement.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStubTests\\Model\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcollectLinks\fP (Node $node)"
.br
.ti -1c
.RI "\fBcollectSinceDeprecatedVersions\fP (Node $node)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBPHPDocElement\fP"
.br
.ti -1c
.RI "\fB$see\fP = []"
.br
.ti -1c
.RI "\fB$sinceTags\fP = []"
.br
.ti -1c
.RI "\fB$deprecatedTags\fP = []"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
