.TH "vendor/nikic/php-parser/lib/PhpParser/Internal/PrintableNewAnonClassNode.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nikic/php-parser/lib/PhpParser/Internal/PrintableNewAnonClassNode.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPrintableNewAnonClassNode\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhpParser\\Internal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
