.TH "vendor/roave/better-reflection/test/unit/Fixture/PrototypeTree.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/PrototypeTree.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBFooInterface\fP"
.br
.ti -1c
.RI "class \fBClassA\fP"
.br
.ti -1c
.RI "class \fBClassB\fP"
.br
.ti -1c
.RI "class \fBClassC\fP"
.br
.ti -1c
.RI "class \fBClassD\fP"
.br
.ti -1c
.RI "class \fBClassE\fP"
.br
.ti -1c
.RI "class \fBClassF\fP"
.br
.ti -1c
.RI "interface \fBBarInterface\fP"
.br
.ti -1c
.RI "class \fBClassT\fP"
.br
.ti -1c
.RI "interface \fBFooInterface\fP"
.br
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBB\fP"
.br
.ti -1c
.RI "interface \fBFooInterface\fP"
.br
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBB\fP"
.br
.ti -1c
.RI "interface \fBFoo\fP"
.br
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "interface \fBFoo\fP"
.br
.ti -1c
.RI "interface \fBBar\fP"
.br
.ti -1c
.RI "interface \fBBoo\fP"
.br
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBB\fP"
.br
.ti -1c
.RI "class \fBFoo\fP"
.br
.ti -1c
.RI "class \fBBar\fP"
.br
.ti -1c
.RI "class \fBLorem\fP"
.br
.ti -1c
.RI "class \fBIpsum\fP"
.br
.ti -1c
.RI "interface \fBFooInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZoom\fP"
.br
.ti -1c
.RI " \fBXoom\fP"
.br
.ti -1c
.RI " \fBFoom\fP"
.br
.ti -1c
.RI " \fBBoom\fP"
.br
.ti -1c
.RI " \fBConstruct\fP"
.br
.ti -1c
.RI " \fBTraits\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBMyTrait\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "trait MyTrait"
\fBInitial value:\fP
.PP
.nf
{
        abstract public function bar()
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
