.TH "vendor/paragonie/random_compat/psalm-autoload.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/paragonie/random_compat/psalm-autoload.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$int\fP = \fBrandom_int\fP(0, 65536)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$int = \fBrandom_int\fP(0, 65536)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
