.TH "vendor/jetbrains/phpstorm-stubs/rar/rar.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/rar/rar.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBRarArchive\fP"
.br
.ti -1c
.RI "class \fBRarEntry\fP"
.br
.ti -1c
.RI "class \fBRarException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
