.TH "vendor/jetbrains/phpstorm-stubs/tests/TestData/Providers/ReflectionTestDataProviders.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/tests/TestData/Providers/ReflectionTestDataProviders.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBReflectionTestDataProviders\fP"
.br
.ti -1c
.RI "class \fBReflectionStubsSingleton\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStubTests\\TestData\\Providers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
