.TH "vendor/psr/http-message/src/ResponseInterface.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/psr/http-message/src/ResponseInterface.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBResponseInterface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPsr\\Http\\Message\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
