.TH "vendor/jetbrains/phpstorm-stubs/SaxonC/SaxonC.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/SaxonC/SaxonC.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSaxonProcessor\fP"
.br
.ti -1c
.RI "class \fBXsltProcessor\fP"
.br
.ti -1c
.RI "class \fBXQueryProcessor\fP"
.br
.ti -1c
.RI "class \fBXPathProcessor\fP"
.br
.ti -1c
.RI "class \fBSchemaValidator\fP"
.br
.ti -1c
.RI "class \fBXdmValue\fP"
.br
.ti -1c
.RI "class \fBXdmItem\fP"
.br
.ti -1c
.RI "class \fBXdmNode\fP"
.br
.ti -1c
.RI "class \fBXdmAtomicValue\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSaxon\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
