.TH "vendor/apigen/apigen/packages/Reflection/tests/Parser/NotLoadedSources/SomeCountableClass.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/Reflection/tests/Parser/NotLoadedSources/SomeCountableClass.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSomeCountableClass\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Reflection\\Tests\\Parser\\NotLoadedSources\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
