.TH "vendor/apigen/apigen/tests/Generator/UsingTraitsSources/SomeClassWithTrait.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/tests/Generator/UsingTraitsSources/SomeClassWithTrait.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSomeClassWithTrait\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\Tests\\Generator\\UsingTraitsSources\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
