.TH "vendor/phpunit/php-code-coverage/tests/_files/source_without_namespace.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-code-coverage/tests/_files/source_without_namespace.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBFoo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "& \fBfoo\fP ($bar)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "& \fBfoo\fP ( $bar)"

.PP
\fBParameters\fP
.RS 4
\fI$bar\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
