.TH "vendor/apigen/apigen/packages/StringRouting/tests/Route/SourceCodeRouteTest.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/apigen/apigen/packages/StringRouting/tests/Route/SourceCodeRouteTest.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSourceCodeRouteTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApiGen\\StringRouting\\Tests\\Route\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
