.TH "vendor/phpunit/php-code-coverage/tests/_files/source_with_ignore.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-code-coverage/tests/_files/source_with_ignore.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBFoo\fP"
.br
.ti -1c
.RI "class \fBBar\fP"
.br
.ti -1c
.RI "interface \fBBor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbaz\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "baz ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
