.TH "vendor/phpunit/php-token-stream/tests/_fixture/source5.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-token-stream/tests/_fixture/source5.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBi\fP"
.br
.ti -1c
.RI "class \fBa\fP"
.br
.ti -1c
.RI "class \fBc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfoo\fP ($\fBa\fP, array $\fBb\fP, array $\fBc\fP=array())"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfoo\fP ( $a, array $b, array $c = \fCarray()\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
