.TH "vendor/phpunit/php-token-stream/tests/_fixture/source3.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-token-stream/tests/_fixture/source3.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$included_files\fP = \fBget_included_files\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$included_files = \fBget_included_files\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
