.TH "vendor/phpunit/php-token-stream/tests/_fixture/source4.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-token-stream/tests/_fixture/source4.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBiTemplate\fP"
.br
.ti -1c
.RI "class \fBa\fP"
.br
.ti -1c
.RI "interface \fBb\fP"
.br
.ti -1c
.RI "class \fBc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
