.TH "vendor/jetbrains/phpstorm-stubs/SPL/SPL.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/SPL/SPL.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBLogicException\fP"
.br
.ti -1c
.RI "class \fBBadFunctionCallException\fP"
.br
.ti -1c
.RI "class \fBBadMethodCallException\fP"
.br
.ti -1c
.RI "class \fBDomainException\fP"
.br
.ti -1c
.RI "class \fBInvalidArgumentException\fP"
.br
.ti -1c
.RI "class \fBLengthException\fP"
.br
.ti -1c
.RI "class \fBOutOfRangeException\fP"
.br
.ti -1c
.RI "class \fBRuntimeException\fP"
.br
.ti -1c
.RI "class \fBOutOfBoundsException\fP"
.br
.ti -1c
.RI "class \fBOverflowException\fP"
.br
.ti -1c
.RI "class \fBRangeException\fP"
.br
.ti -1c
.RI "class \fBUnderflowException\fP"
.br
.ti -1c
.RI "class \fBUnexpectedValueException\fP"
.br
.ti -1c
.RI "class \fBEmptyIterator\fP"
.br
.ti -1c
.RI "class \fBCallbackFilterIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveCallbackFilterIterator\fP"
.br
.ti -1c
.RI "interface \fBRecursiveIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveIteratorIterator\fP"
.br
.ti -1c
.RI "interface \fBOuterIterator\fP"
.br
.ti -1c
.RI "class \fBIteratorIterator\fP"
.br
.ti -1c
.RI "class \fBFilterIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveFilterIterator\fP"
.br
.ti -1c
.RI "class \fBParentIterator\fP"
.br
.ti -1c
.RI "interface \fBSeekableIterator\fP"
.br
.ti -1c
.RI "class \fBLimitIterator\fP"
.br
.ti -1c
.RI "class \fBCachingIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveCachingIterator\fP"
.br
.ti -1c
.RI "class \fBNoRewindIterator\fP"
.br
.ti -1c
.RI "class \fBAppendIterator\fP"
.br
.ti -1c
.RI "class \fBInfiniteIterator\fP"
.br
.ti -1c
.RI "class \fBRegexIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveRegexIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveTreeIterator\fP"
.br
.ti -1c
.RI "class \fBArrayObject\fP"
.br
.ti -1c
.RI "class \fBArrayIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveArrayIterator\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBMT_RAND_MT19937\fP 0"
.br
.ti -1c
.RI "const \fBMT_RAND_PHP\fP 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const MT_RAND_MT19937 0"

.PP
\fBSince\fP
.RS 4
7\&.1 
.RE
.PP

.SS "const MT_RAND_PHP 1"

.PP
\fBSince\fP
.RS 4
7\&.1 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
