.TH "vendor/jetbrains/phpstorm-stubs/SPL/SPL_c1.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/SPL/SPL_c1.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSplFileInfo\fP"
.br
.ti -1c
.RI "class \fBDirectoryIterator\fP"
.br
.ti -1c
.RI "class \fBFilesystemIterator\fP"
.br
.ti -1c
.RI "class \fBRecursiveDirectoryIterator\fP"
.br
.ti -1c
.RI "class \fBGlobIterator\fP"
.br
.ti -1c
.RI "class \fBSplFileObject\fP"
.br
.ti -1c
.RI "class \fBSplTempFileObject\fP"
.br
.ti -1c
.RI "class \fBSplDoublyLinkedList\fP"
.br
.ti -1c
.RI "class \fBSplQueue\fP"
.br
.ti -1c
.RI "class \fBSplStack\fP"
.br
.ti -1c
.RI "class \fBSplHeap\fP"
.br
.ti -1c
.RI "class \fBSplMinHeap\fP"
.br
.ti -1c
.RI "class \fBSplMaxHeap\fP"
.br
.ti -1c
.RI "class \fBSplPriorityQueue\fP"
.br
.ti -1c
.RI "class \fBSplFixedArray\fP"
.br
.ti -1c
.RI "interface \fBSplObserver\fP"
.br
.ti -1c
.RI "interface \fBSplSubject\fP"
.br
.ti -1c
.RI "class \fBSplObjectStorage\fP"
.br
.ti -1c
.RI "class \fBMultipleIterator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
