.TH "vendor/jetbrains/phpstorm-stubs/SplType/SplType.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/SplType/SplType.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSplType\fP"
.br
.ti -1c
.RI "class \fBSplInt\fP"
.br
.ti -1c
.RI "class \fBSplFloat\fP"
.br
.ti -1c
.RI "class \fBSplEnum\fP"
.br
.ti -1c
.RI "class \fBSplBool\fP"
.br
.ti -1c
.RI "class \fBSplString\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
