.TH "vendor/jetbrains/phpstorm-stubs/standard/standard_defines.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/standard/standard_defines.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBCONNECTION_ABORTED\fP 1"
.br
.ti -1c
.RI "const \fBCONNECTION_NORMAL\fP 0"
.br
.ti -1c
.RI "const \fBCONNECTION_TIMEOUT\fP 2"
.br
.ti -1c
.RI "const \fBINI_USER\fP 1"
.br
.ti -1c
.RI "const \fBINI_PERDIR\fP 2"
.br
.ti -1c
.RI "const \fBINI_SYSTEM\fP 4"
.br
.ti -1c
.RI "const \fBINI_ALL\fP 7"
.br
.ti -1c
.RI "const \fBINI_SCANNER_NORMAL\fP 0"
.br
.ti -1c
.RI "const \fBINI_SCANNER_TYPED\fP 2"
.br
.ti -1c
.RI "const \fBINI_SCANNER_RAW\fP 1"
.br
.ti -1c
.RI "const \fBPHP_URL_SCHEME\fP 0"
.br
.ti -1c
.RI "const \fBPHP_URL_HOST\fP 1"
.br
.ti -1c
.RI "const \fBPHP_URL_PORT\fP 2"
.br
.ti -1c
.RI "const \fBPHP_URL_USER\fP 3"
.br
.ti -1c
.RI "const \fBPHP_URL_PASS\fP 4"
.br
.ti -1c
.RI "const \fBPHP_URL_PATH\fP 5"
.br
.ti -1c
.RI "const \fBPHP_URL_QUERY\fP 6"
.br
.ti -1c
.RI "const \fBPHP_URL_FRAGMENT\fP 7"
.br
.ti -1c
.RI "const \fBM_E\fP 2\&.718281828459"
.br
.ti -1c
.RI "const \fBM_LOG2E\fP 1\&.442695040889"
.br
.ti -1c
.RI "const \fBM_LOG10E\fP 0\&.43429448190325"
.br
.ti -1c
.RI "const \fBM_LN2\fP 0\&.69314718055995"
.br
.ti -1c
.RI "const \fBM_LN10\fP 2\&.302585092994"
.br
.ti -1c
.RI "const \fBM_PI\fP 3\&.1415926535898"
.br
.ti -1c
.RI "const \fBM_PI_2\fP 1\&.5707963267949"
.br
.ti -1c
.RI "const \fBM_PI_4\fP 0\&.78539816339745"
.br
.ti -1c
.RI "const \fBM_1_PI\fP 0\&.31830988618379"
.br
.ti -1c
.RI "const \fBM_2_PI\fP 0\&.63661977236758"
.br
.ti -1c
.RI "const \fBM_SQRTPI\fP 1\&.7724538509055"
.br
.ti -1c
.RI "const \fBM_2_SQRTPI\fP 1\&.1283791670955"
.br
.ti -1c
.RI "const \fBM_LNPI\fP 1\&.1447298858494"
.br
.ti -1c
.RI "const \fBM_EULER\fP 0\&.57721566490153"
.br
.ti -1c
.RI "const \fBM_SQRT2\fP 1\&.4142135623731"
.br
.ti -1c
.RI "const \fBM_SQRT1_2\fP 0\&.70710678118655"
.br
.ti -1c
.RI "const \fBM_SQRT3\fP 1\&.7320508075689"
.br
.ti -1c
.RI "const \fBINF\fP INF"
.br
.ti -1c
.RI "const \fBNAN\fP NAN"
.br
.ti -1c
.RI "const \fBPHP_ROUND_HALF_UP\fP 1"
.br
.ti -1c
.RI "const \fBPHP_ROUND_HALF_DOWN\fP 2"
.br
.ti -1c
.RI "const \fBPHP_ROUND_HALF_EVEN\fP 3"
.br
.ti -1c
.RI "const \fBPHP_ROUND_HALF_ODD\fP 4"
.br
.ti -1c
.RI "const \fBINFO_GENERAL\fP 1"
.br
.ti -1c
.RI "const \fBINFO_CREDITS\fP 2"
.br
.ti -1c
.RI "const \fBINFO_CONFIGURATION\fP 4"
.br
.ti -1c
.RI "const \fBINFO_MODULES\fP 8"
.br
.ti -1c
.RI "const \fBINFO_ENVIRONMENT\fP 16"
.br
.ti -1c
.RI "const \fBINFO_VARIABLES\fP 32"
.br
.ti -1c
.RI "const \fBINFO_LICENSE\fP 64"
.br
.ti -1c
.RI "const \fBINFO_ALL\fP 4294967295"
.br
.ti -1c
.RI "const \fBCREDITS_GROUP\fP 1"
.br
.ti -1c
.RI "const \fBCREDITS_GENERAL\fP 2"
.br
.ti -1c
.RI "const \fBCREDITS_SAPI\fP 4"
.br
.ti -1c
.RI "const \fBCREDITS_MODULES\fP 8"
.br
.ti -1c
.RI "const \fBCREDITS_DOCS\fP 16"
.br
.ti -1c
.RI "const \fBCREDITS_FULLPAGE\fP 32"
.br
.ti -1c
.RI "const \fBCREDITS_QA\fP 64"
.br
.ti -1c
.RI "const \fBCREDITS_ALL\fP 4294967295"
.br
.ti -1c
.RI "const \fBHTML_SPECIALCHARS\fP 0"
.br
.ti -1c
.RI "const \fBHTML_ENTITIES\fP 1"
.br
.ti -1c
.RI "const \fBENT_COMPAT\fP 2"
.br
.ti -1c
.RI "const \fBENT_QUOTES\fP 3"
.br
.ti -1c
.RI "const \fBENT_NOQUOTES\fP 0"
.br
.ti -1c
.RI "const \fBENT_IGNORE\fP 4"
.br
.ti -1c
.RI "const \fBSTR_PAD_LEFT\fP 0"
.br
.ti -1c
.RI "const \fBSTR_PAD_RIGHT\fP 1"
.br
.ti -1c
.RI "const \fBSTR_PAD_BOTH\fP 2"
.br
.ti -1c
.RI "const \fBPATHINFO_DIRNAME\fP 1"
.br
.ti -1c
.RI "const \fBPATHINFO_BASENAME\fP 2"
.br
.ti -1c
.RI "const \fBPATHINFO_EXTENSION\fP 4"
.br
.ti -1c
.RI "const \fBPATHINFO_FILENAME\fP 8"
.br
.ti -1c
.RI "const \fBCHAR_MAX\fP 127"
.br
.ti -1c
.RI "const \fBLC_CTYPE\fP 0"
.br
.ti -1c
.RI "const \fBLC_NUMERIC\fP 1"
.br
.ti -1c
.RI "const \fBLC_TIME\fP 2"
.br
.ti -1c
.RI "const \fBLC_COLLATE\fP 3"
.br
.ti -1c
.RI "const \fBLC_MONETARY\fP 4"
.br
.ti -1c
.RI "const \fBLC_ALL\fP 6"
.br
.ti -1c
.RI "const \fBLC_MESSAGES\fP 5"
.br
.ti -1c
.RI "const \fBSEEK_SET\fP 0"
.br
.ti -1c
.RI "const \fBSEEK_CUR\fP 1"
.br
.ti -1c
.RI "const \fBSEEK_END\fP 2"
.br
.ti -1c
.RI "const \fBLOCK_SH\fP 1"
.br
.ti -1c
.RI "const \fBLOCK_EX\fP 2"
.br
.ti -1c
.RI "const \fBLOCK_UN\fP 3"
.br
.ti -1c
.RI "const \fBLOCK_NB\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_CONNECT\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_AUTH_REQUIRED\fP 3"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_AUTH_RESULT\fP 10"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_MIME_TYPE_IS\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_FILE_SIZE_IS\fP 5"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_REDIRECTED\fP 6"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_PROGRESS\fP 7"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_FAILURE\fP 9"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_COMPLETED\fP 8"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_RESOLVE\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_SEVERITY_INFO\fP 0"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_SEVERITY_WARN\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_NOTIFY_SEVERITY_ERR\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_FILTER_READ\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_FILTER_WRITE\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_FILTER_ALL\fP 3"
.br
.ti -1c
.RI "const \fBSTREAM_CLIENT_PERSISTENT\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_CLIENT_ASYNC_CONNECT\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_CLIENT_CONNECT\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_SHUT_RD\fP 0"
.br
.ti -1c
.RI "const \fBSTREAM_SHUT_WR\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_SHUT_RDWR\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_PF_INET\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_PF_INET6\fP 10"
.br
.ti -1c
.RI "const \fBSTREAM_PF_UNIX\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_IPPROTO_IP\fP 0"
.br
.ti -1c
.RI "const \fBSTREAM_IPPROTO_TCP\fP 6"
.br
.ti -1c
.RI "const \fBSTREAM_IPPROTO_UDP\fP 17"
.br
.ti -1c
.RI "const \fBSTREAM_IPPROTO_ICMP\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_IPPROTO_RAW\fP 255"
.br
.ti -1c
.RI "const \fBSTREAM_SOCK_STREAM\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_SOCK_DGRAM\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_SOCK_RAW\fP 3"
.br
.ti -1c
.RI "const \fBSTREAM_SOCK_SEQPACKET\fP 5"
.br
.ti -1c
.RI "const \fBSTREAM_SOCK_RDM\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_PEEK\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_OOB\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_SERVER_BIND\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_SERVER_LISTEN\fP 8"
.br
.ti -1c
.RI "const \fBFILE_USE_INCLUDE_PATH\fP 1"
.br
.ti -1c
.RI "const \fBFILE_IGNORE_NEW_LINES\fP 2"
.br
.ti -1c
.RI "const \fBFILE_SKIP_EMPTY_LINES\fP 4"
.br
.ti -1c
.RI "const \fBFILE_APPEND\fP 8"
.br
.ti -1c
.RI "const \fBFILE_NO_DEFAULT_CONTEXT\fP 16"
.br
.ti -1c
.RI "const \fBFILE_TEXT\fP 0"
.br
.ti -1c
.RI "const \fBFILE_BINARY\fP 0"
.br
.ti -1c
.RI "const \fBFNM_NOESCAPE\fP 2"
.br
.ti -1c
.RI "const \fBFNM_PATHNAME\fP 1"
.br
.ti -1c
.RI "const \fBFNM_PERIOD\fP 4"
.br
.ti -1c
.RI "const \fBFNM_CASEFOLD\fP 16"
.br
.ti -1c
.RI "const \fBPSFS_PASS_ON\fP 2"
.br
.ti -1c
.RI "const \fBPSFS_FEED_ME\fP 1"
.br
.ti -1c
.RI "const \fBPSFS_ERR_FATAL\fP 0"
.br
.ti -1c
.RI "const \fBPSFS_FLAG_NORMAL\fP 0"
.br
.ti -1c
.RI "const \fBPSFS_FLAG_FLUSH_INC\fP 1"
.br
.ti -1c
.RI "const \fBPSFS_FLAG_FLUSH_CLOSE\fP 2"
.br
.ti -1c
.RI "const \fBABDAY_1\fP 131072"
.br
.ti -1c
.RI "const \fBABDAY_2\fP 131073"
.br
.ti -1c
.RI "const \fBABDAY_3\fP 131074"
.br
.ti -1c
.RI "const \fBABDAY_4\fP 131075"
.br
.ti -1c
.RI "const \fBABDAY_5\fP 131076"
.br
.ti -1c
.RI "const \fBABDAY_6\fP 131077"
.br
.ti -1c
.RI "const \fBABDAY_7\fP 131078"
.br
.ti -1c
.RI "const \fBDAY_1\fP 131079"
.br
.ti -1c
.RI "const \fBDAY_2\fP 131080"
.br
.ti -1c
.RI "const \fBDAY_3\fP 131081"
.br
.ti -1c
.RI "const \fBDAY_4\fP 131082"
.br
.ti -1c
.RI "const \fBDAY_5\fP 131083"
.br
.ti -1c
.RI "const \fBDAY_6\fP 131084"
.br
.ti -1c
.RI "const \fBDAY_7\fP 131085"
.br
.ti -1c
.RI "const \fBABMON_1\fP 131086"
.br
.ti -1c
.RI "const \fBABMON_2\fP 131087"
.br
.ti -1c
.RI "const \fBABMON_3\fP 131088"
.br
.ti -1c
.RI "const \fBABMON_4\fP 131089"
.br
.ti -1c
.RI "const \fBABMON_5\fP 131090"
.br
.ti -1c
.RI "const \fBABMON_6\fP 131091"
.br
.ti -1c
.RI "const \fBABMON_7\fP 131092"
.br
.ti -1c
.RI "const \fBABMON_8\fP 131093"
.br
.ti -1c
.RI "const \fBABMON_9\fP 131094"
.br
.ti -1c
.RI "const \fBABMON_10\fP 131095"
.br
.ti -1c
.RI "const \fBABMON_11\fP 131096"
.br
.ti -1c
.RI "const \fBABMON_12\fP 131097"
.br
.ti -1c
.RI "const \fBMON_1\fP 131098"
.br
.ti -1c
.RI "const \fBMON_2\fP 131099"
.br
.ti -1c
.RI "const \fBMON_3\fP 131100"
.br
.ti -1c
.RI "const \fBMON_4\fP 131101"
.br
.ti -1c
.RI "const \fBMON_5\fP 131102"
.br
.ti -1c
.RI "const \fBMON_6\fP 131103"
.br
.ti -1c
.RI "const \fBMON_7\fP 131104"
.br
.ti -1c
.RI "const \fBMON_8\fP 131105"
.br
.ti -1c
.RI "const \fBMON_9\fP 131106"
.br
.ti -1c
.RI "const \fBMON_10\fP 131107"
.br
.ti -1c
.RI "const \fBMON_11\fP 131108"
.br
.ti -1c
.RI "const \fBMON_12\fP 131109"
.br
.ti -1c
.RI "const \fBAM_STR\fP 131110"
.br
.ti -1c
.RI "const \fBPM_STR\fP 131111"
.br
.ti -1c
.RI "const \fBD_T_FMT\fP 131112"
.br
.ti -1c
.RI "const \fBD_FMT\fP 131113"
.br
.ti -1c
.RI "const \fBT_FMT\fP 131114"
.br
.ti -1c
.RI "const \fBT_FMT_AMPM\fP 131115"
.br
.ti -1c
.RI "const \fBERA\fP 131116"
.br
.ti -1c
.RI "const \fBERA_D_T_FMT\fP 131120"
.br
.ti -1c
.RI "const \fBERA_D_FMT\fP 131118"
.br
.ti -1c
.RI "const \fBERA_T_FMT\fP 131121"
.br
.ti -1c
.RI "const \fBALT_DIGITS\fP 131119"
.br
.ti -1c
.RI "const \fBCRNCYSTR\fP 262159"
.br
.ti -1c
.RI "const \fBRADIXCHAR\fP 65536"
.br
.ti -1c
.RI "const \fBTHOUSEP\fP 65537"
.br
.ti -1c
.RI "const \fBYESEXPR\fP 327680"
.br
.ti -1c
.RI "const \fBNOEXPR\fP 327681"
.br
.ti -1c
.RI "const \fBYESSTR\fP 54"
.br
.ti -1c
.RI "const \fBNOSTR\fP 55"
.br
.ti -1c
.RI "const \fBCODESET\fP 14"
.br
.ti -1c
.RI "const \fBCRYPT_SALT_LENGTH\fP 123"
.br
.ti -1c
.RI "const \fBCRYPT_STD_DES\fP 1"
.br
.ti -1c
.RI "const \fBCRYPT_EXT_DES\fP 1"
.br
.ti -1c
.RI "const \fBCRYPT_MD5\fP 1"
.br
.ti -1c
.RI "const \fBCRYPT_BLOWFISH\fP 1"
.br
.ti -1c
.RI "const \fBCRYPT_SHA256\fP 1"
.br
.ti -1c
.RI "const \fBCRYPT_SHA512\fP 1"
.br
.ti -1c
.RI "const \fBDIRECTORY_SEPARATOR\fP '/'"
.br
.ti -1c
.RI "const \fBPATH_SEPARATOR\fP ':'"
.br
.ti -1c
.RI "const \fBGLOB_BRACE\fP 1024"
.br
.ti -1c
.RI "const \fBGLOB_MARK\fP 2"
.br
.ti -1c
.RI "const \fBGLOB_NOSORT\fP 4"
.br
.ti -1c
.RI "const \fBGLOB_NOCHECK\fP 16"
.br
.ti -1c
.RI "const \fBGLOB_NOESCAPE\fP 64"
.br
.ti -1c
.RI "const \fBGLOB_ERR\fP 1"
.br
.ti -1c
.RI "const \fBGLOB_ONLYDIR\fP 8192"
.br
.ti -1c
.RI "const \fBGLOB_AVAILABLE_FLAGS\fP 9303"
.br
.ti -1c
.RI "const \fBEXTR_OVERWRITE\fP 0"
.br
.ti -1c
.RI "const \fBEXTR_SKIP\fP 1"
.br
.ti -1c
.RI "const \fBEXTR_PREFIX_SAME\fP 2"
.br
.ti -1c
.RI "const \fBEXTR_PREFIX_ALL\fP 3"
.br
.ti -1c
.RI "const \fBEXTR_PREFIX_INVALID\fP 4"
.br
.ti -1c
.RI "const \fBEXTR_PREFIX_IF_EXISTS\fP 5"
.br
.ti -1c
.RI "const \fBEXTR_IF_EXISTS\fP 6"
.br
.ti -1c
.RI "const \fBEXTR_REFS\fP 256"
.br
.ti -1c
.RI "const \fBSORT_ASC\fP 4"
.br
.ti -1c
.RI "const \fBSORT_DESC\fP 3"
.br
.ti -1c
.RI "const \fBSORT_REGULAR\fP 0"
.br
.ti -1c
.RI "const \fBSORT_NUMERIC\fP 1"
.br
.ti -1c
.RI "const \fBSORT_STRING\fP 2"
.br
.ti -1c
.RI "const \fBSORT_LOCALE_STRING\fP 5"
.br
.ti -1c
.RI "const \fBCASE_LOWER\fP 0"
.br
.ti -1c
.RI "const \fBCASE_UPPER\fP 1"
.br
.ti -1c
.RI "const \fBCOUNT_NORMAL\fP 0"
.br
.ti -1c
.RI "const \fBCOUNT_RECURSIVE\fP 1"
.br
.ti -1c
.RI "const \fBASSERT_ACTIVE\fP 1"
.br
.ti -1c
.RI "const \fBASSERT_CALLBACK\fP 2"
.br
.ti -1c
.RI "const \fBASSERT_BAIL\fP 3"
.br
.ti -1c
.RI "const \fBASSERT_WARNING\fP 4"
.br
.ti -1c
.RI "const \fBASSERT_QUIET_EVAL\fP 5"
.br
.ti -1c
.RI "const \fBASSERT_EXCEPTION\fP 6"
.br
.ti -1c
.RI "const \fBSTREAM_USE_PATH\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_IGNORE_URL\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_ENFORCE_SAFE_MODE\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_REPORT_ERRORS\fP 8"
.br
.ti -1c
.RI "const \fBSTREAM_MUST_SEEK\fP 16"
.br
.ti -1c
.RI "const \fBSTREAM_URL_STAT_LINK\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_URL_STAT_QUIET\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_MKDIR_RECURSIVE\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_IS_URL\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_OPTION_BLOCKING\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_OPTION_READ_TIMEOUT\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_OPTION_READ_BUFFER\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_OPTION_WRITE_BUFFER\fP 3"
.br
.ti -1c
.RI "const \fBSTREAM_BUFFER_NONE\fP 0"
.br
.ti -1c
.RI "const \fBSTREAM_BUFFER_LINE\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_BUFFER_FULL\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_CAST_AS_STREAM\fP 0"
.br
.ti -1c
.RI "const \fBSTREAM_CAST_FOR_SELECT\fP 3"
.br
.ti -1c
.RI "const \fBIMAGETYPE_GIF\fP 1"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JPEG\fP 2"
.br
.ti -1c
.RI "const \fBIMAGETYPE_PNG\fP 3"
.br
.ti -1c
.RI "const \fBIMAGETYPE_SWF\fP 4"
.br
.ti -1c
.RI "const \fBIMAGETYPE_PSD\fP 5"
.br
.ti -1c
.RI "const \fBIMAGETYPE_BMP\fP 6"
.br
.ti -1c
.RI "const \fBIMAGETYPE_TIFF_II\fP 7"
.br
.ti -1c
.RI "const \fBIMAGETYPE_TIFF_MM\fP 8"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JPC\fP 9"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JP2\fP 10"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JPX\fP 11"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JB2\fP 12"
.br
.ti -1c
.RI "const \fBIMAGETYPE_SWC\fP 13"
.br
.ti -1c
.RI "const \fBIMAGETYPE_IFF\fP 14"
.br
.ti -1c
.RI "const \fBIMAGETYPE_WBMP\fP 15"
.br
.ti -1c
.RI "const \fBIMAGETYPE_JPEG2000\fP 9"
.br
.ti -1c
.RI "const \fBIMAGETYPE_XBM\fP 16"
.br
.ti -1c
.RI "const \fBIMAGETYPE_ICO\fP 17"
.br
.ti -1c
.RI "const \fBIMAGETYPE_WEBP\fP 18"
.br
.ti -1c
.RI "const \fBIMAGETYPE_UNKNOWN\fP 0"
.br
.ti -1c
.RI "const \fBIMAGETYPE_COUNT\fP 19"
.br
.ti -1c
.RI "const \fBDNS_A\fP 1"
.br
.ti -1c
.RI "const \fBDNS_CAA\fP 8192"
.br
.ti -1c
.RI "const \fBDNS_NS\fP 2"
.br
.ti -1c
.RI "const \fBDNS_CNAME\fP 16"
.br
.ti -1c
.RI "const \fBDNS_SOA\fP 32"
.br
.ti -1c
.RI "const \fBDNS_PTR\fP 2048"
.br
.ti -1c
.RI "const \fBDNS_HINFO\fP 4096"
.br
.ti -1c
.RI "const \fBDNS_MX\fP 16384"
.br
.ti -1c
.RI "const \fBDNS_TXT\fP 32768"
.br
.ti -1c
.RI "const \fBDNS_SRV\fP 33554432"
.br
.ti -1c
.RI "const \fBDNS_NAPTR\fP 67108864"
.br
.ti -1c
.RI "const \fBDNS_AAAA\fP 134217728"
.br
.ti -1c
.RI "const \fBDNS_A6\fP 16777216"
.br
.ti -1c
.RI "const \fBDNS_ANY\fP 268435456"
.br
.ti -1c
.RI "const \fBDNS_ALL\fP 251721779"
.br
.ti -1c
.RI "const \fBPHP_QUERY_RFC1738\fP 1"
.br
.ti -1c
.RI "const \fBPHP_QUERY_RFC3986\fP 2"
.br
.ti -1c
.RI "const \fBPHP_MANDIR\fP '/usr/local/\fBphp\fP/\fBphp\fP/man'"
.br
.ti -1c
.RI "const \fBPHP_BINARY\fP '/usr/local/\fBphp\fP/bin/\fBphp\fP'"
.br
.ti -1c
.RI "const \fBPHP_CLI_PROCESS_TITLE\fP 1"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_WRITE\fP 0"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_FLUSH\fP 4"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_CLEAN\fP 2"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_FINAL\fP 8"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_CLEANABLE\fP 16"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_FLUSHABLE\fP 32"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_REMOVABLE\fP 64"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_STDFLAGS\fP 112"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_STARTED\fP 4096"
.br
.ti -1c
.RI "const \fBPHP_OUTPUT_HANDLER_DISABLED\fP 8192"
.br
.ti -1c
.RI "const \fBSID\fP 'name=ID'"
.br
.ti -1c
.RI "const \fBPHP_SESSION_DISABLED\fP 0"
.br
.ti -1c
.RI "const \fBPHP_SESSION_NONE\fP 1"
.br
.ti -1c
.RI "const \fBPHP_SESSION_ACTIVE\fP 2"
.br
.ti -1c
.RI "const \fBENT_SUBSTITUTE\fP 8"
.br
.ti -1c
.RI "const \fBENT_DISALLOWED\fP 128"
.br
.ti -1c
.RI "const \fBENT_HTML401\fP 0"
.br
.ti -1c
.RI "const \fBENT_XML1\fP 16"
.br
.ti -1c
.RI "const \fBENT_XHTML\fP 32"
.br
.ti -1c
.RI "const \fBENT_HTML5\fP 48"
.br
.ti -1c
.RI "const \fBSCANDIR_SORT_ASCENDING\fP 0"
.br
.ti -1c
.RI "const \fBSCANDIR_SORT_DESCENDING\fP 1"
.br
.ti -1c
.RI "const \fBSCANDIR_SORT_NONE\fP 2"
.br
.ti -1c
.RI "const \fBSORT_NATURAL\fP 6"
.br
.ti -1c
.RI "const \fBSORT_FLAG_CASE\fP 8"
.br
.ti -1c
.RI "const \fBSTREAM_META_TOUCH\fP 1"
.br
.ti -1c
.RI "const \fBSTREAM_META_OWNER\fP 3"
.br
.ti -1c
.RI "const \fBSTREAM_META_OWNER_NAME\fP 2"
.br
.ti -1c
.RI "const \fBSTREAM_META_GROUP\fP 5"
.br
.ti -1c
.RI "const \fBSTREAM_META_GROUP_NAME\fP 4"
.br
.ti -1c
.RI "const \fBSTREAM_META_ACCESS\fP 6"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const ABDAY_1 131072"

.SS "const ABDAY_2 131073"

.SS "const ABDAY_3 131074"

.SS "const ABDAY_4 131075"

.SS "const ABDAY_5 131076"

.SS "const ABDAY_6 131077"

.SS "const ABDAY_7 131078"

.SS "const ABMON_1 131086"

.SS "const ABMON_10 131095"

.SS "const ABMON_11 131096"

.SS "const ABMON_12 131097"

.SS "const ABMON_2 131087"

.SS "const ABMON_3 131088"

.SS "const ABMON_4 131089"

.SS "const ABMON_5 131090"

.SS "const ABMON_6 131091"

.SS "const ABMON_7 131092"

.SS "const ABMON_8 131093"

.SS "const ABMON_9 131094"

.SS "const ALT_DIGITS 131119"

.SS "const AM_STR 131110"

.SS "const ASSERT_ACTIVE 1"

.SS "const ASSERT_BAIL 3"

.SS "const ASSERT_CALLBACK 2"

.SS "const ASSERT_EXCEPTION 6"

.SS "const ASSERT_QUIET_EVAL 5"

.SS "const ASSERT_WARNING 4"

.SS "const CASE_LOWER 0"
CASE_LOWER is used with array_change_key_case and is used to convert array keys to lower case\&. This is also the default case for array_change_key_case\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const CASE_UPPER 1"
CASE_UPPER is used with array_change_key_case and is used to convert array keys to upper case\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const CHAR_MAX 127"

.SS "const CODESET 14"

.SS "const CONNECTION_ABORTED 1"

.SS "const CONNECTION_NORMAL 0"

.SS "const CONNECTION_TIMEOUT 2"

.SS "const COUNT_NORMAL 0"

.SS "const COUNT_RECURSIVE 1"

.SS "const CREDITS_ALL 4294967295"
The configuration line, &php\&.ini; location, build date, Web Server, System and more\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_DOCS 16"
The credits for the documentation team\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_FULLPAGE 32"
Usually used in combination with the other flags\&. Indicates that a complete stand-alone HTML page needs to be printed including the information indicated by the other flags\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_GENERAL 2"
General credits: Language design and concept, PHP authors and SAPI module\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_GROUP 1"
\fBA\fP list of the core developers \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_MODULES 8"
\fBA\fP list of the extension modules for PHP, and their authors\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_QA 64"
The credits for the quality assurance team\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CREDITS_SAPI 4"
\fBA\fP list of the server API modules for PHP, and their authors\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const CRNCYSTR 262159"

.SS "const CRYPT_BLOWFISH 1"

.SS "const CRYPT_EXT_DES 1"

.SS "const CRYPT_MD5 1"

.SS "const CRYPT_SALT_LENGTH 123"

.SS "const CRYPT_SHA256 1"

.SS "const CRYPT_SHA512 1"

.SS "const CRYPT_STD_DES 1"

.SS "const D_FMT 131113"

.SS "const D_T_FMT 131112"

.SS "const DAY_1 131079"

.SS "const DAY_2 131080"

.SS "const DAY_3 131081"

.SS "const DAY_4 131082"

.SS "const DAY_5 131083"

.SS "const DAY_6 131084"

.SS "const DAY_7 131085"

.SS "const DIRECTORY_SEPARATOR '/'"

.SS "const DNS_A 1"
IPv4 Address Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_A6 16777216"

.SS "const DNS_AAAA 134217728"
IPv6 Address Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_ALL 251721779"
Iteratively query the name server for each available record type\&. \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_ANY 268435456"
Any Resource Record\&. On most systems this returns all resource records, however it should not be counted upon for critical uses\&. Try DNS_ALL instead\&. \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_CAA 8192"

.SS "const DNS_CNAME 16"
Alias (Canonical Name) Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_HINFO 4096"
Host Info Resource (See IANA's Operating System Names for the meaning of these values) \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_MX 16384"
Mail Exchanger Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_NAPTR 67108864"

.SS "const DNS_NS 2"
Authoritative Name Server Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_PTR 2048"
Pointer Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_SOA 32"
Start of Authority Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const DNS_SRV 33554432"

.SS "const DNS_TXT 32768"
Text Resource \fBhttps://php\&.net/manual/en/network\&.constants\&.php\fP
.SS "const ENT_COMPAT 2"
Will convert double-quotes and leave single-quotes alone\&. \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.SS "const ENT_DISALLOWED 128"
Replace invalid code points for the given document type with a Unicode Replacement Character U+FFFD (UTF-8) or &#FFFD; (otherwise) instead of leaving them as is\&. This may be useful, for instance, to ensure the well-formedness of XML documents with embedded external content\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ENT_HTML401 0"
Handle code as HTML 4\&.01\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ENT_HTML5 48"
Handle code as HTML 5\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ENT_IGNORE 4"
Silently discard invalid code unit sequences instead of returning an empty string\&. Using this flag is discouraged as it may have security implications\&. \fB5\&.3 \fP
.SS "const ENT_NOQUOTES 0"
Will leave both double and single quotes unconverted\&. \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.SS "const ENT_QUOTES 3"
Will convert both double and single quotes\&. \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.SS "const ENT_SUBSTITUTE 8"
Replace invalid code unit sequences with a Unicode Replacement Character U+FFFD (UTF-8) or &#FFFD; (otherwise) instead of returning an empty string\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ENT_XHTML 32"
Handle code as XHTML\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ENT_XML1 16"
Handle code as XML 1\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.htmlspecialchars\&.php\fP
.RE
.PP

.SS "const ERA 131116"

.SS "const ERA_D_FMT 131118"

.SS "const ERA_D_T_FMT 131120"

.SS "const ERA_T_FMT 131121"

.SS "const EXTR_IF_EXISTS 6"

.SS "const EXTR_OVERWRITE 0"

.SS "const EXTR_PREFIX_ALL 3"

.SS "const EXTR_PREFIX_IF_EXISTS 5"

.SS "const EXTR_PREFIX_INVALID 4"

.SS "const EXTR_PREFIX_SAME 2"

.SS "const EXTR_REFS 256"

.SS "const EXTR_SKIP 1"

.SS "const FILE_APPEND 8"
Append content to existing file\&. \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FILE_BINARY 0"
This constant has no effect prior to PHP 6\&. It is only available for forward compatibility\&. 
.PP
\fBSince\fP
.RS 4
5\&.2\&.7 \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.RE
.PP

.SS "const FILE_IGNORE_NEW_LINES 2"
Strip EOL characters \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FILE_NO_DEFAULT_CONTEXT 16"

.SS "const FILE_SKIP_EMPTY_LINES 4"
Skip empty lines \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FILE_TEXT 0"
This constant has no effect prior to PHP 6\&. It is only available for forward compatibility\&. 
.PP
\fBSince\fP
.RS 4
5\&.2\&.7 \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.RE
.PP

.SS "const FILE_USE_INCLUDE_PATH 1"
Search for filename in include_path \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FNM_CASEFOLD 16"
Caseless match\&. Part of the GNU extension\&. \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FNM_NOESCAPE 2"
Disable backslash escaping\&. \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FNM_PATHNAME 1"
Slash in string only matches slash in the given pattern\&. \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const FNM_PERIOD 4"
Leading period in string must be exactly matched by period in the given pattern\&. \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.SS "const GLOB_AVAILABLE_FLAGS 9303"

.SS "const GLOB_BRACE 1024"

.SS "const GLOB_ERR 1"

.SS "const GLOB_MARK 2"

.SS "const GLOB_NOCHECK 16"

.SS "const GLOB_NOESCAPE 64"

.SS "const GLOB_NOSORT 4"

.SS "const GLOB_ONLYDIR 8192"

.SS "const HTML_ENTITIES 1"

.SS "const HTML_SPECIALCHARS 0"

.SS "const IMAGETYPE_BMP 6"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_COUNT 19"

.SS "const IMAGETYPE_GIF 1"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_ICO 17"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fB5\&.3 \fP
.SS "const IMAGETYPE_IFF 14"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JB2 12"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JP2 10"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JPC 9"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JPEG 2"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JPEG2000 9"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_JPX 11"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_PNG 3"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_PSD 5"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_SWC 13"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_SWF 4"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_TIFF_II 7"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_TIFF_MM 8"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_UNKNOWN 0"

.SS "const IMAGETYPE_WBMP 15"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const IMAGETYPE_WEBP 18"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fB7\&.1 \fP
.SS "const IMAGETYPE_XBM 16"
Image type constant used by the \fBimage_type_to_mime_type()\fP and \fBimage_type_to_extension()\fP functions\&. \fBhttps://php\&.net/manual/en/image\&.constants\&.php\fP
.SS "const INF INF"
The infinite 
.SS "const INFO_ALL 4294967295"

.SS "const INFO_CONFIGURATION 4"
Current Local and Master values for PHP directives\&. See also ini_get\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INFO_CREDITS 2"
PHP Credits\&. See also phpcredits\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INFO_ENVIRONMENT 16"
Environment Variable information that's also available in $_ENV\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INFO_GENERAL 1"

.SS "const INFO_LICENSE 64"
PHP License information\&. See also the license faq\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INFO_MODULES 8"
Loaded modules and their respective settings\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INFO_VARIABLES 32"
Shows all predefined variables from EGPCS (Environment, GET, POST, Cookie, Server)\&. \fBhttps://php\&.net/manual/en/info\&.constants\&.php\fP
.SS "const INI_ALL 7"

.SS "const INI_PERDIR 2"

.SS "const INI_SCANNER_NORMAL 0"
Normal INI scanner mode 
.PP
\fBSince\fP
.RS 4
5\&.3 \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.RE
.PP

.SS "const INI_SCANNER_RAW 1"
Raw INI scanner mode 
.PP
\fBSince\fP
.RS 4
5\&.3 \fBhttps://php\&.net/manual/en/filesystem\&.constants\&.php\fP
.RE
.PP

.SS "const INI_SCANNER_TYPED 2"
Typed INI scanner mode 
.PP
\fBSince\fP
.RS 4
5\&.6\&.1 \fBhttps://php\&.net/manual/en/function\&.parse-ini-file\&.php\fP
.RE
.PP

.SS "const INI_SYSTEM 4"

.SS "const INI_USER 1"

.SS "const LC_ALL 6"

.SS "const LC_COLLATE 3"

.SS "const LC_CTYPE 0"

.SS "const LC_MESSAGES 5"

.SS "const LC_MONETARY 4"

.SS "const LC_NUMERIC 1"

.SS "const LC_TIME 2"

.SS "const LOCK_EX 2"
Acquire an exclusive lock (writer)\&. \fBhttps://www\&.php\&.net/manual/en/function\&.flock\&.php\fP
.SS "const LOCK_NB 4"
Non-blocking operation while locking\&. \fBhttps://www\&.php\&.net/manual/en/function\&.flock\&.php\fP
.SS "const LOCK_SH 1"
Acquire a shared lock (reader)\&. \fBhttps://www\&.php\&.net/manual/en/function\&.flock\&.php\fP
.SS "const LOCK_UN 3"
Release lock (shared or exclusive)\&. \fBhttps://www\&.php\&.net/manual/en/function\&.flock\&.php\fP
.SS "const M_1_PI 0\&.31830988618379"
1/ constant 
.SS "const M_2_PI 0\&.63661977236758"
2/ constant 
.SS "const M_2_SQRTPI 1\&.1283791670955"
2/\fBsqrt\fP() constant 
.SS "const M_E 2\&.718281828459"
\fIe\fP constant 
.SS "const M_EULER 0\&.57721566490153"
Euler constant 
.SS "const M_LN10 2\&.302585092994"
\fBlog\fP\*<\fIe\fP\*> 10 constant 
.SS "const M_LN2 0\&.69314718055995"
\fBlog\fP\*<\fIe\fP\*> 2 constant 
.SS "const M_LNPI 1\&.1447298858494"
\fBlog\fP\*<\fIe\fP\*>  constant 
.SS "const M_LOG10E 0\&.43429448190325"
\fBlog\fP\*<10\*> \fIe\fP constant 
.SS "const M_LOG2E 1\&.442695040889"
\fBlog\fP\*<2\*> \fIe\fP constant 
.SS "const M_PI 3\&.1415926535898"
 constant 
.SS "const M_PI_2 1\&.5707963267949"
/2 constant 
.SS "const M_PI_4 0\&.78539816339745"
/4 constant 
.SS "const M_SQRT1_2 0\&.70710678118655"
1/\fBsqrt\fP(2) constant 
.SS "const M_SQRT2 1\&.4142135623731"
\fBsqrt\fP(2) constant 
.SS "const M_SQRT3 1\&.7320508075689"
\fBsqrt\fP(3) constant 
.SS "const M_SQRTPI 1\&.7724538509055"
\fBsqrt\fP() constant 
.SS "const MON_1 131098"

.SS "const MON_10 131107"

.SS "const MON_11 131108"

.SS "const MON_12 131109"

.SS "const MON_2 131099"

.SS "const MON_3 131100"

.SS "const MON_4 131101"

.SS "const MON_5 131102"

.SS "const MON_6 131103"

.SS "const MON_7 131104"

.SS "const MON_8 131105"

.SS "const MON_9 131106"

.SS "const NAN NAN"
Not \fBA\fP Number 
.SS "const NOEXPR 327681"

.SS "const NOSTR 55"

.SS "const PATH_SEPARATOR ':'"

.SS "const PATHINFO_BASENAME 2"

.SS "const PATHINFO_DIRNAME 1"

.SS "const PATHINFO_EXTENSION 4"

.SS "const PATHINFO_FILENAME 8"
\fB5\&.2 \fP
.SS "const PHP_BINARY '/usr/local/\fBphp\fP/bin/\fBphp\fP'"
Specifies where the binaries were installed into\&. \fBhttps://php\&.net/manual/en/reserved\&.constants\&.php\fP
.SS "const PHP_CLI_PROCESS_TITLE 1"

.PP
\fBSince\fP
.RS 4
7\&.4 
.RE
.PP

.SS "const PHP_MANDIR '/usr/local/\fBphp\fP/\fBphp\fP/man'"
Specifies where the manpages were installed into\&. 
.PP
\fBSince\fP
.RS 4
PHP 5\&.3\&.7 \fBhttps://php\&.net/manual/en/reserved\&.constants\&.php\fP
.RE
.PP

.SS "const PHP_OUTPUT_HANDLER_CLEAN 2"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_CLEANABLE 16"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_DISABLED 8192"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_FINAL 8"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_FLUSH 4"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_FLUSHABLE 32"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_REMOVABLE 64"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_STARTED 4096"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_STDFLAGS 112"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_OUTPUT_HANDLER_WRITE 0"
\fBhttps://php\&.net/manual/en/outcontrol\&.constants\&.php\fP
.SS "const PHP_QUERY_RFC1738 1"
Encoding is performed per RFC 1738 and the application/x-www-form-urlencoded media type, which implies that spaces are encoded as plus (+) signs\&. \fBhttps://php\&.net/manual/en/function\&.http-build-query\&.php\fP
.SS "const PHP_QUERY_RFC3986 2"
Encoding is performed according to RFC 3986, and spaces will be percent encoded (%20)\&. \fBhttps://php\&.net/manual/en/function\&.http-build-query\&.php\fP
.SS "const PHP_ROUND_HALF_DOWN 2"
Round halves down \fB5\&.3 \fP
.SS "const PHP_ROUND_HALF_EVEN 3"
Round halves to even numbers \fB5\&.3 \fP
.SS "const PHP_ROUND_HALF_ODD 4"
Round halves to odd numbers \fB5\&.3 \fP
.SS "const PHP_ROUND_HALF_UP 1"
Round halves up \fB5\&.3 \fP
.SS "const PHP_SESSION_ACTIVE 2"
Return value of \fBsession_status()\fP if sessions are enabled, and a session exists\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.session-status\&.php\fP
.RE
.PP

.SS "const PHP_SESSION_DISABLED 0"
Return value of \fBsession_status()\fP if sessions are disabled\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.session-status\&.php\fP
.RE
.PP

.SS "const PHP_SESSION_NONE 1"
Return value of \fBsession_status()\fP if sessions are enabled, but no session exists\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/function\&.session-status\&.php\fP
.RE
.PP

.SS "const PHP_URL_FRAGMENT 7"

.SS "const PHP_URL_HOST 1"

.SS "const PHP_URL_PASS 4"

.SS "const PHP_URL_PATH 5"

.SS "const PHP_URL_PORT 2"

.SS "const PHP_URL_QUERY 6"

.SS "const PHP_URL_SCHEME 0"

.SS "const PHP_URL_USER 3"

.SS "const PM_STR 131111"

.SS "const PSFS_ERR_FATAL 0"
Return Code indicating that the userspace filter encountered an unrecoverable error (i\&.e\&. Invalid data received)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const PSFS_FEED_ME 1"
Return Code indicating that the userspace filter did not return buckets in $out (i\&.e\&. No data available)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const PSFS_FLAG_FLUSH_CLOSE 2"
Final flush prior to closing\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const PSFS_FLAG_FLUSH_INC 1"
An incremental flush\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const PSFS_FLAG_NORMAL 0"
Regular read/write\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const PSFS_PASS_ON 2"
Return Code indicating that the userspace filter returned buckets in $out\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const RADIXCHAR 65536"

.SS "const SCANDIR_SORT_ASCENDING 0"
\fBhttps://php\&.net/manual/en/function\&.scandir\&.php\fP
.SS "const SCANDIR_SORT_DESCENDING 1"
\fBhttps://php\&.net/manual/en/function\&.scandir\&.php\fP
.SS "const SCANDIR_SORT_NONE 2"
\fBhttps://php\&.net/manual/en/function\&.scandir\&.php\fP
.SS "const SEEK_CUR 1"

.SS "const SEEK_END 2"

.SS "const SEEK_SET 0"

.SS "const SID 'name=ID'"
(PHP4, PHP5) 
.PP
Constant containing either the session name and session ID in the form of 'name=ID' or empty string if session ID was set in an appropriate session cookie\&. This is the same id as the one returned by \fBsession_id()\fP\&. 
.PP
\fBSee also\fP
.RS 4
\fBsession_id()\fP \fBhttps://php\&.net/manual/en/session\&.constants\&.php\fP
.RE
.PP

.SS "const SORT_ASC 4"
SORT_ASC is used with array_multisort to sort in ascending order\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const SORT_DESC 3"
SORT_DESC is used with array_multisort to sort in descending order\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const SORT_FLAG_CASE 8"
SORT_FLAG_CASE can be combined (bitwise OR) with SORT_STRING or SORT_NATURAL to sort strings case-insensitively\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.RE
.PP

.SS "const SORT_LOCALE_STRING 5"
SORT_LOCALE_STRING is used to compare items as strings, based on the current locale\&. 
.PP
\fBSince\fP
.RS 4
4\&.4 
.PP
5\&.0\&.2 \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.RE
.PP

.SS "const SORT_NATURAL 6"
SORT_NATURAL is used to compare items as strings using 'natural ordering' like \fBnatsort()\fP\&. 
.PP
\fBSince\fP
.RS 4
5\&.4 \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.RE
.PP

.SS "const SORT_NUMERIC 1"
SORT_NUMERIC is used to compare items numerically\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const SORT_REGULAR 0"
SORT_REGULAR is used to compare items normally\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const SORT_STRING 2"
SORT_STRING is used to compare items as strings\&. \fBhttps://php\&.net/manual/en/array\&.constants\&.php\fP
.SS "const STR_PAD_BOTH 2"

.SS "const STR_PAD_LEFT 0"

.SS "const STR_PAD_RIGHT 1"

.SS "const STREAM_BUFFER_FULL 2"

.SS "const STREAM_BUFFER_LINE 1"

.SS "const STREAM_BUFFER_NONE 0"

.SS "const STREAM_CAST_AS_STREAM 0"
Stream casting, when stream_cast is called otherwise (see above)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_CAST_FOR_SELECT 3"
Stream casting, for when stream_select is calling stream_cast\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_CLIENT_ASYNC_CONNECT 2"
Open client socket asynchronously\&. This option must be used together with the STREAM_CLIENT_CONNECT flag\&. Used with stream_socket_client\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_CLIENT_CONNECT 4"
Open client socket connection\&. Client sockets should always include this flag\&. Used with stream_socket_client\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_CLIENT_PERSISTENT 1"
Client socket opened with stream_socket_client should remain persistent between page loads\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_ENFORCE_SAFE_MODE 4"

.SS "const STREAM_FILTER_ALL 3"
This constant is equivalent to STREAM_FILTER_READ | STREAM_FILTER_WRITE \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_FILTER_READ 1"
Used with stream_filter_append and stream_filter_prepend to indicate that the specified filter should only be applied when reading \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_FILTER_WRITE 2"
Used with stream_filter_append and stream_filter_prepend to indicate that the specified filter should only be applied when writing \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IGNORE_URL 2"

.SS "const STREAM_IPPROTO_ICMP 1"
Provides a ICMP socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IPPROTO_IP 0"
Provides a IP socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IPPROTO_RAW 255"
Provides a RAW socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IPPROTO_TCP 6"
Provides a TCP socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IPPROTO_UDP 17"
Provides a UDP socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_IS_URL 1"

.SS "const STREAM_META_ACCESS 6"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_META_GROUP 5"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_META_GROUP_NAME 4"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_META_OWNER 3"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_META_OWNER_NAME 2"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_META_TOUCH 1"
\fBhttps://php\&.net/manual/en/streamwrapper\&.stream-metadata\&.php\fP
.SS "const STREAM_MKDIR_RECURSIVE 1"

.SS "const STREAM_MUST_SEEK 16"
This flag is useful when your extension really must be able to randomly seek around in a stream\&. Some streams may not be seekable in their native form, so this flag asks the streams API to check to see if the stream does support seeking\&. If it does not, it will copy the stream into temporary storage (which may be a temporary file or a memory stream) which does support seeking\&. Please note that this flag is not useful when you want to seek the stream and write to it, because the stream you are accessing might not be bound to the actual resource you requested\&. If the requested resource is network based, this flag will cause the opener to block until the whole contents have been downloaded\&. \fBhttps://php\&.net/manual/en/internals2\&.ze1\&.streams\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_AUTH_REQUIRED 3"
Additional authorization is required to access the specified resource\&. Typical issued with severity level of STREAM_NOTIFY_SEVERITY_ERR\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_AUTH_RESULT 10"
Authorization has been completed (with or without success)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_COMPLETED 8"
There is no more data available on the stream\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_CONNECT 2"
\fBA\fP connection with an external resource has been established\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_FAILURE 9"
\fBA\fP generic error occurred on the stream, consult message and message_code for details\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_FILE_SIZE_IS 5"
The size of the resource has been discovered\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_MIME_TYPE_IS 4"
The mime-type of resource has been identified, refer to message for a description of the discovered type\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_PROGRESS 7"
Indicates current progress of the stream transfer in bytes_transferred and possibly bytes_max as well\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_REDIRECTED 6"
The external resource has redirected the stream to an alternate location\&. Refer to message\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_RESOLVE 1"
\fBA\fP remote address required for this stream has been resolved, or the resolution failed\&. See severity for an indication of which happened\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_SEVERITY_ERR 2"
\fBA\fP critical error occurred\&. Processing cannot continue\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_SEVERITY_INFO 0"
Normal, non-error related, notification\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_NOTIFY_SEVERITY_WARN 1"
Non critical error condition\&. Processing may continue\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_OOB 1"

.SS "const STREAM_OPTION_BLOCKING 1"

.SS "const STREAM_OPTION_READ_BUFFER 2"

.SS "const STREAM_OPTION_READ_TIMEOUT 4"

.SS "const STREAM_OPTION_WRITE_BUFFER 3"

.SS "const STREAM_PEEK 2"

.SS "const STREAM_PF_INET 2"
Internet Protocol Version 4 (IPv4)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_PF_INET6 10"
Internet Protocol Version 6 (IPv6)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_PF_UNIX 1"
Unix system internal protocols\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_REPORT_ERRORS 8"
Flag indicating if the wrapper is responsible for raising errors using trigger_error during opening of the stream\&. If this flag is not set, you should not raise any errors\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SERVER_BIND 4"
Tells a stream created with stream_socket_server to bind to the specified target\&. Server sockets should always include this flag\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SERVER_LISTEN 8"
Tells a stream created with stream_socket_server and bound using the STREAM_SERVER_BIND flag to start listening on the socket\&. Connection-orientated transports (such as TCP) must use this flag, otherwise the server socket will not be enabled\&. Using this flag for connect-less transports (such as UDP) is an error\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SHUT_RD 0"
Used with stream_socket_shutdown to disable further receptions\&. 
.PP
\fBSince\fP
.RS 4
5\&.2\&.1 \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.RE
.PP

.SS "const STREAM_SHUT_RDWR 2"
Used with stream_socket_shutdown to disable further receptions and transmissions\&. 
.PP
\fBSince\fP
.RS 4
5\&.2\&.1 \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.RE
.PP

.SS "const STREAM_SHUT_WR 1"
Used with stream_socket_shutdown to disable further transmissions\&. 
.PP
\fBSince\fP
.RS 4
5\&.2\&.1 \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.RE
.PP

.SS "const STREAM_SOCK_DGRAM 2"
Provides datagrams, which are connectionless messages (UDP, for example)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SOCK_RAW 3"
Provides a raw socket, which provides access to internal network protocols and interfaces\&. Usually this type of socket is just available to the root user\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SOCK_RDM 4"
Provides a RDM (Reliably-delivered messages) socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SOCK_SEQPACKET 5"
Provides a sequenced packet stream socket\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_SOCK_STREAM 1"
Provides sequenced, two-way byte streams with a transmission mechanism for out-of-band data (TCP, for example)\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const STREAM_URL_STAT_LINK 1"

.SS "const STREAM_URL_STAT_QUIET 2"

.SS "const STREAM_USE_PATH 1"
Flag indicating if the stream used the include path\&. \fBhttps://php\&.net/manual/en/stream\&.constants\&.php\fP
.SS "const T_FMT 131114"

.SS "const T_FMT_AMPM 131115"

.SS "const THOUSEP 65537"

.SS "const YESEXPR 327680"

.SS "const YESSTR 54"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
