.TH "vendor/roave/better-reflection/test/unit/Fixture/StringCastClassObjectExpected.txt" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/roave/better-reflection/test/unit/Fixture/StringCastClassObjectExpected.txt
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBStringCastClassObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
