.TH "vendor/symfony/polyfill-util/TestListener.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/polyfill-util/TestListener.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSymfony\\Polyfill\\Util\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(\fBclass_exists\fP('PHPUnit_Runner_Version') &&\fBversion_compare\fP(\\PHPUnit_Runner_Version::id(), '6\&.0\&.0', '<')) elseif(\fBversion_compare\fP(\\\fBPHPUnit\\Runner\\Version::id\fP(), '7\&.0\&.0', '<')) \fBelse\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
