.TH "vendor/phpunit/php-timer/src/Timer.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-timer/src/Timer.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPHP_Timer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(isset($_SERVER['REQUEST_TIME_FLOAT'])) elseif(isset($_SERVER['REQUEST_TIME'])) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (isset( $_SERVER[ 'REQUEST_TIME_FLOAT'])) elseif (isset( $_SERVER[ 'REQUEST_TIME'])) else"
\fBInitial value:\fP
.PP
.nf
{
    PHP_Timer::$requestTime = microtime(true)
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
