.TH "vendor/jetbrains/phpstorm-stubs/couchbase/toplevel.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/couchbase/toplevel.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBCOUCHBASE_PERSISTTO_MASTER\fP 1"
.br
.ti -1c
.RI "const \fBCOUCHBASE_PERSISTTO_ONE\fP 1"
.br
.ti -1c
.RI "const \fBCOUCHBASE_PERSISTTO_TWO\fP 2"
.br
.ti -1c
.RI "const \fBCOUCHBASE_PERSISTTO_THREE\fP 4"
.br
.ti -1c
.RI "const \fBCOUCHBASE_REPLICATETO_ONE\fP 16"
.br
.ti -1c
.RI "const \fBCOUCHBASE_REPLICATETO_TWO\fP 32"
.br
.ti -1c
.RI "const \fBCOUCHBASE_REPLICATETO_THREE\fP 64"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUCCESS\fP 0"
.br
.ti -1c
.RI "const \fBCOUCHBASE_AUTH_CONTINUE\fP 1"
.br
.ti -1c
.RI "const \fBCOUCHBASE_AUTH_ERROR\fP 2"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DELTA_BADVAL\fP 3"
.br
.ti -1c
.RI "const \fBCOUCHBASE_E2BIG\fP 4"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EBUSY\fP 5"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EINTERNAL\fP 6"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EINVAL\fP 7"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ENOMEM\fP 8"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ERANGE\fP 9"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ERROR\fP 10"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ETMPFAIL\fP 11"
.br
.ti -1c
.RI "const \fBCOUCHBASE_KEY_EEXISTS\fP 12"
.br
.ti -1c
.RI "const \fBCOUCHBASE_KEY_ENOENT\fP 13"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DLOPEN_FAILED\fP 14"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DLSYM_FAILED\fP 15"
.br
.ti -1c
.RI "const \fBCOUCHBASE_NETWORK_ERROR\fP 16"
.br
.ti -1c
.RI "const \fBCOUCHBASE_NOT_MY_VBUCKET\fP 17"
.br
.ti -1c
.RI "const \fBCOUCHBASE_NOT_STORED\fP 18"
.br
.ti -1c
.RI "const \fBCOUCHBASE_NOT_SUPPORTED\fP 19"
.br
.ti -1c
.RI "const \fBCOUCHBASE_UNKNOWN_COMMAND\fP 20"
.br
.ti -1c
.RI "const \fBCOUCHBASE_UNKNOWN_HOST\fP 21"
.br
.ti -1c
.RI "const \fBCOUCHBASE_PROTOCOL_ERROR\fP 22"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ETIMEDOUT\fP 23"
.br
.ti -1c
.RI "const \fBCOUCHBASE_CONNECT_ERROR\fP 24"
.br
.ti -1c
.RI "const \fBCOUCHBASE_BUCKET_ENOENT\fP 25"
.br
.ti -1c
.RI "const \fBCOUCHBASE_CLIENT_ENOMEM\fP 26"
.br
.ti -1c
.RI "const \fBCOUCHBASE_CLIENT_ENOCONF\fP 27"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EBADHANDLE\fP 28"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SERVER_BUG\fP 29"
.br
.ti -1c
.RI "const \fBCOUCHBASE_PLUGIN_VERSION_MISMATCH\fP 30"
.br
.ti -1c
.RI "const \fBCOUCHBASE_INVALID_HOST_FORMAT\fP 31"
.br
.ti -1c
.RI "const \fBCOUCHBASE_INVALID_CHAR\fP 32"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DURABILITY_ETOOMANY\fP 33"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DUPLICATE_COMMANDS\fP 34"
.br
.ti -1c
.RI "const \fBCOUCHBASE_NO_MATCHING_SERVER\fP 35"
.br
.ti -1c
.RI "const \fBCOUCHBASE_BAD_ENVIRONMENT\fP 36"
.br
.ti -1c
.RI "const \fBCOUCHBASE_BUSY\fP 37"
.br
.ti -1c
.RI "const \fBCOUCHBASE_INVALID_USERNAME\fP 38"
.br
.ti -1c
.RI "const \fBCOUCHBASE_CONFIG_CACHE_INVALID\fP 39"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SASLMECH_UNAVAILABLE\fP 40"
.br
.ti -1c
.RI "const \fBCOUCHBASE_TOO_MANY_REDIRECTS\fP 41"
.br
.ti -1c
.RI "const \fBCOUCHBASE_MAP_CHANGED\fP 42"
.br
.ti -1c
.RI "const \fBCOUCHBASE_INCOMPLETE_PACKET\fP 43"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECONNREFUSED\fP 44"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ESOCKSHUTDOWN\fP 45"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECONNRESET\fP 46"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECANTGETPORT\fP 47"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EFDLIMITREACHED\fP 48"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ENETUNREACH\fP 49"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECTL_UNKNOWN\fP 50"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECTL_UNSUPPMODE\fP 51"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ECTL_BADARG\fP 52"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EMPTY_KEY\fP 53"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SSL_ERROR\fP 54"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SSL_CANTVERIFY\fP 55"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SCHEDFAIL_INTERNAL\fP 56"
.br
.ti -1c
.RI "const \fBCOUCHBASE_CLIENT_FEATURE_UNAVAILABLE\fP 57"
.br
.ti -1c
.RI "const \fBCOUCHBASE_OPTIONS_CONFLICT\fP 58"
.br
.ti -1c
.RI "const \fBCOUCHBASE_HTTP_ERROR\fP 59"
.br
.ti -1c
.RI "const \fBCOUCHBASE_DURABILITY_NO_MUTATION_TOKENS\fP 60"
.br
.ti -1c
.RI "const \fBCOUCHBASE_UNKNOWN_MEMCACHED_ERROR\fP 61"
.br
.ti -1c
.RI "const \fBCOUCHBASE_MUTATION_LOST\fP 62"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_PATH_ENOENT\fP 63"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_PATH_MISMATCH\fP 64"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_PATH_EINVAL\fP 65"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_PATH_E2BIG\fP 66"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_DOC_E2DEEP\fP 67"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_VALUE_CANTINSERT\fP 68"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_DOC_NOTJSON\fP 69"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_NUM_ERANGE\fP 70"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_BAD_DELTA\fP 71"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_PATH_EEXISTS\fP 72"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_MULTI_FAILURE\fP 73"
.br
.ti -1c
.RI "const \fBCOUCHBASE_SUBDOC_VALUE_E2DEEP\fP 74"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EINVAL_MCD\fP 75"
.br
.ti -1c
.RI "const \fBCOUCHBASE_EMPTY_PATH\fP 76"
.br
.ti -1c
.RI "const \fBCOUCHBASE_UNKNOWN_SDCMD\fP 77"
.br
.ti -1c
.RI "const \fBCOUCHBASE_ENO_COMMANDS\fP 78"
.br
.ti -1c
.RI "const \fBCOUCHBASE_QUERY_ERROR\fP 79"
.br
.ti -1c
.RI "const \fBCOUCHBASE_TMPFAIL\fP 11"
.br
.ti -1c
.RI "const \fBCOUCHBASE_KEYALREADYEXISTS\fP 12"
.br
.ti -1c
.RI "const \fBCOUCHBASE_KEYNOTFOUND\fP 13"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const COUCHBASE_AUTH_CONTINUE 1"

.SS "const COUCHBASE_AUTH_ERROR 2"

.SS "const COUCHBASE_BAD_ENVIRONMENT 36"

.SS "const COUCHBASE_BUCKET_ENOENT 25"

.SS "const COUCHBASE_BUSY 37"

.SS "const COUCHBASE_CLIENT_ENOCONF 27"

.SS "const COUCHBASE_CLIENT_ENOMEM 26"

.SS "const COUCHBASE_CLIENT_FEATURE_UNAVAILABLE 57"

.SS "const COUCHBASE_CONFIG_CACHE_INVALID 39"

.SS "const COUCHBASE_CONNECT_ERROR 24"

.SS "const COUCHBASE_DELTA_BADVAL 3"

.SS "const COUCHBASE_DLOPEN_FAILED 14"

.SS "const COUCHBASE_DLSYM_FAILED 15"

.SS "const COUCHBASE_DUPLICATE_COMMANDS 34"

.SS "const COUCHBASE_DURABILITY_ETOOMANY 33"

.SS "const COUCHBASE_DURABILITY_NO_MUTATION_TOKENS 60"

.SS "const COUCHBASE_E2BIG 4"

.SS "const COUCHBASE_EBADHANDLE 28"

.SS "const COUCHBASE_EBUSY 5"

.SS "const COUCHBASE_ECANTGETPORT 47"

.SS "const COUCHBASE_ECONNREFUSED 44"

.SS "const COUCHBASE_ECONNRESET 46"

.SS "const COUCHBASE_ECTL_BADARG 52"

.SS "const COUCHBASE_ECTL_UNKNOWN 50"

.SS "const COUCHBASE_ECTL_UNSUPPMODE 51"

.SS "const COUCHBASE_EFDLIMITREACHED 48"

.SS "const COUCHBASE_EINTERNAL 6"

.SS "const COUCHBASE_EINVAL 7"

.SS "const COUCHBASE_EINVAL_MCD 75"

.SS "const COUCHBASE_EMPTY_KEY 53"

.SS "const COUCHBASE_EMPTY_PATH 76"

.SS "const COUCHBASE_ENETUNREACH 49"

.SS "const COUCHBASE_ENO_COMMANDS 78"

.SS "const COUCHBASE_ENOMEM 8"

.SS "const COUCHBASE_ERANGE 9"

.SS "const COUCHBASE_ERROR 10"

.SS "const COUCHBASE_ESOCKSHUTDOWN 45"

.SS "const COUCHBASE_ETIMEDOUT 23"

.SS "const COUCHBASE_ETMPFAIL 11"

.SS "const COUCHBASE_HTTP_ERROR 59"

.SS "const COUCHBASE_INCOMPLETE_PACKET 43"

.SS "const COUCHBASE_INVALID_CHAR 32"

.SS "const COUCHBASE_INVALID_HOST_FORMAT 31"

.SS "const COUCHBASE_INVALID_USERNAME 38"

.SS "const COUCHBASE_KEY_EEXISTS 12"

.SS "const COUCHBASE_KEY_ENOENT 13"

.SS "const COUCHBASE_KEYALREADYEXISTS 12"

.SS "const COUCHBASE_KEYNOTFOUND 13"

.SS "const COUCHBASE_MAP_CHANGED 42"

.SS "const COUCHBASE_MUTATION_LOST 62"

.SS "const COUCHBASE_NETWORK_ERROR 16"

.SS "const COUCHBASE_NO_MATCHING_SERVER 35"

.SS "const COUCHBASE_NOT_MY_VBUCKET 17"

.SS "const COUCHBASE_NOT_STORED 18"

.SS "const COUCHBASE_NOT_SUPPORTED 19"

.SS "const COUCHBASE_OPTIONS_CONFLICT 58"

.SS "const COUCHBASE_PERSISTTO_MASTER 1"

.SS "const COUCHBASE_PERSISTTO_ONE 1"

.SS "const COUCHBASE_PERSISTTO_THREE 4"

.SS "const COUCHBASE_PERSISTTO_TWO 2"

.SS "const COUCHBASE_PLUGIN_VERSION_MISMATCH 30"

.SS "const COUCHBASE_PROTOCOL_ERROR 22"

.SS "const COUCHBASE_QUERY_ERROR 79"

.SS "const COUCHBASE_REPLICATETO_ONE 16"

.SS "const COUCHBASE_REPLICATETO_THREE 64"

.SS "const COUCHBASE_REPLICATETO_TWO 32"

.SS "const COUCHBASE_SASLMECH_UNAVAILABLE 40"

.SS "const COUCHBASE_SCHEDFAIL_INTERNAL 56"

.SS "const COUCHBASE_SERVER_BUG 29"

.SS "const COUCHBASE_SSL_CANTVERIFY 55"

.SS "const COUCHBASE_SSL_ERROR 54"

.SS "const COUCHBASE_SUBDOC_BAD_DELTA 71"

.SS "const COUCHBASE_SUBDOC_DOC_E2DEEP 67"

.SS "const COUCHBASE_SUBDOC_DOC_NOTJSON 69"

.SS "const COUCHBASE_SUBDOC_MULTI_FAILURE 73"

.SS "const COUCHBASE_SUBDOC_NUM_ERANGE 70"

.SS "const COUCHBASE_SUBDOC_PATH_E2BIG 66"

.SS "const COUCHBASE_SUBDOC_PATH_EEXISTS 72"

.SS "const COUCHBASE_SUBDOC_PATH_EINVAL 65"

.SS "const COUCHBASE_SUBDOC_PATH_ENOENT 63"

.SS "const COUCHBASE_SUBDOC_PATH_MISMATCH 64"

.SS "const COUCHBASE_SUBDOC_VALUE_CANTINSERT 68"

.SS "const COUCHBASE_SUBDOC_VALUE_E2DEEP 74"

.SS "const COUCHBASE_SUCCESS 0"

.SS "const COUCHBASE_TMPFAIL 11"

.SS "const COUCHBASE_TOO_MANY_REDIRECTS 41"

.SS "const COUCHBASE_UNKNOWN_COMMAND 20"

.SS "const COUCHBASE_UNKNOWN_HOST 21"

.SS "const COUCHBASE_UNKNOWN_MEMCACHED_ERROR 61"

.SS "const COUCHBASE_UNKNOWN_SDCMD 77"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
