.TH "vendor/nette/php-generator/src/PhpGenerator/Traits/VisibilityAware.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nette/php-generator/src/PhpGenerator/Traits/VisibilityAware.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNette\\PhpGenerator\\Traits\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetVisibility\fP (?string $val)"
.br
.ti -1c
.RI "\fBgetVisibility\fP ()"
.br
.ti -1c
.RI "\fBsetPublic\fP ()"
.br
.ti -1c
.RI "\fBisPublic\fP ()"
.br
.ti -1c
.RI "\fBsetProtected\fP ()"
.br
.ti -1c
.RI "\fBisProtected\fP ()"
.br
.ti -1c
.RI "\fBsetPrivate\fP ()"
.br
.ti -1c
.RI "\fBisPrivate\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBVisibilityAware\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
