.TH "vendor/jetbrains/phpstorm-stubs/xsl/xsl.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/xsl/xsl.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXSLTProcessor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBXSL_CLONE_AUTO\fP 0"
.br
.ti -1c
.RI "const \fBXSL_CLONE_NEVER\fP \-1"
.br
.ti -1c
.RI "const \fBXSL_CLONE_ALWAYS\fP 1"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_NONE\fP 0"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_READ_FILE\fP 2"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_WRITE_FILE\fP 4"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_CREATE_DIRECTORY\fP 8"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_READ_NETWORK\fP 16"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_WRITE_NETWORK\fP 32"
.br
.ti -1c
.RI "const \fBXSL_SECPREF_DEFAULT\fP 44"
.br
.ti -1c
.RI "const \fBLIBXSLT_VERSION\fP 10128"
.br
.ti -1c
.RI "const \fBLIBXSLT_DOTTED_VERSION\fP '1\&.1\&.28'"
.br
.ti -1c
.RI "const \fBLIBEXSLT_VERSION\fP 817"
.br
.ti -1c
.RI "const \fBLIBEXSLT_DOTTED_VERSION\fP '1\&.1\&.28'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const LIBEXSLT_DOTTED_VERSION '1\&.1\&.28'"
libexslt version like 1\&.1\&.17\&. Available as of PHP 5\&.1\&.2\&. \fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const LIBEXSLT_VERSION 817"
libexslt version like 813\&. Available as of PHP 5\&.1\&.2\&. \fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const LIBXSLT_DOTTED_VERSION '1\&.1\&.28'"
libxslt version like 1\&.1\&.17\&. Available as of PHP 5\&.1\&.2\&. \fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const LIBXSLT_VERSION 10128"
libxslt version like 10117\&. Available as of PHP 5\&.1\&.2\&. \fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_CLONE_ALWAYS 1"

.SS "const XSL_CLONE_AUTO 0"

.SS "const XSL_CLONE_NEVER \-1"

.SS "const XSL_SECPREF_CREATE_DIRECTORY 8"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_DEFAULT 44"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_NONE 0"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_READ_FILE 2"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_READ_NETWORK 16"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_WRITE_FILE 4"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SS "const XSL_SECPREF_WRITE_NETWORK 32"
\fBhttps://php\&.net/manual/en/xsl\&.constants\&.php\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
