.TH "vendor/jetbrains/phpstorm-stubs/xxtea/xxtea.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/xxtea/xxtea.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBXXTEA\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBxxtea_encrypt\fP ($data, $\fBkey\fP)"
.br
.ti -1c
.RI "\fBxxtea_decrypt\fP ($data, $\fBkey\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "xxtea_decrypt ( $data,  $key)"
Decrypts data\&.
.PP
\fBParameters\fP
.RS 4
\fI$data\fP Data to be decrypted 
.br
\fI$key\fP Encryption key
.RE
.PP
\fBReturns\fP
.RS 4
string|false
.RE
.PP
\fBSince\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SS "xxtea_encrypt ( $data,  $key)"
Encrypts data\&.
.PP
\fBParameters\fP
.RS 4
\fI$data\fP Data to be encrypted 
.br
\fI$key\fP Encryption key
.RE
.PP
\fBReturns\fP
.RS 4
string
.RE
.PP
\fBSince\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
