.TH "vendor/jetbrains/phpstorm-stubs/yaf/yaf_namespace.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/yaf/yaf_namespace.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBApplication\fP"
.br
.ti -1c
.RI "class \fBDispatcher\fP"
.br
.ti -1c
.RI "class \fBLoader\fP"
.br
.ti -1c
.RI "class \fBRegistry\fP"
.br
.ti -1c
.RI "class \fBSession\fP"
.br
.ti -1c
.RI "class \fBRouter\fP"
.br
.ti -1c
.RI "class \fBBootstrap_Abstract\fP"
.br
.ti -1c
.RI "class \fBController_Abstract\fP"
.br
.ti -1c
.RI "class \fBAction_Abstract\fP"
.br
.ti -1c
.RI "class \fBConfig_Abstract\fP"
.br
.ti -1c
.RI "class \fBRequest_Abstract\fP"
.br
.ti -1c
.RI "class \fBPlugin_Abstract\fP"
.br
.ti -1c
.RI "class \fBResponse_Abstract\fP"
.br
.ti -1c
.RI "interface \fBView_Interface\fP"
.br
.ti -1c
.RI "interface \fBRoute_Interface\fP"
.br
.ti -1c
.RI "class \fBException\fP"
.br
.ti -1c
.RI "class \fBRoute_Static\fP"
.br
.ti -1c
.RI "class \fBHttp\fP"
.br
.ti -1c
.RI "class \fBCli\fP"
.br
.ti -1c
.RI "class \fBHttp\fP"
.br
.ti -1c
.RI "class \fBSimple\fP"
.br
.ti -1c
.RI "class \fBIni\fP"
.br
.ti -1c
.RI "class \fBSimple\fP"
.br
.ti -1c
.RI "class \fBSimple\fP"
.br
.ti -1c
.RI "class \fBSimple\fP"
.br
.ti -1c
.RI "class \fBSupervar\fP"
.br
.ti -1c
.RI "class \fBRewrite\fP"
.br
.ti -1c
.RI "class \fBRegex\fP"
.br
.ti -1c
.RI "class \fBMap\fP"
.br
.ti -1c
.RI "class \fBException\\TypeError\fP"
.br
.ti -1c
.RI "class \fBException\\StartupError\fP"
.br
.ti -1c
.RI "class \fBException\\RouterFailed\fP"
.br
.ti -1c
.RI "class \fBException\\DispatchFailed\fP"
.br
.ti -1c
.RI "class \fBException\\LoadFailed\fP"
.br
.ti -1c
.RI "class \fBException\\LoadFailed\\Module\fP"
.br
.ti -1c
.RI "class \fBException\\LoadFailed\\Controller\fP"
.br
.ti -1c
.RI "class \fBException\\LoadFailed\\Action\fP"
.br
.ti -1c
.RI "class \fBException\\LoadFailed\\View\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBYaf\fP"
.br
.ti -1c
.RI " \fBYaf\\Response\fP"
.br
.ti -1c
.RI " \fBYaf\\Request\fP"
.br
.ti -1c
.RI " \fBYaf\\Config\fP"
.br
.ti -1c
.RI " \fBYaf\\View\fP"
.br
.ti -1c
.RI " \fBYaf\\Route\fP"
.br
.ti -1c
.RI " \fBYaf\\Exception\fP"
.br
.ti -1c
.RI " \fBYaf\\Exception\\LoadFailed\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBVERSION\fP '3\&.0\&.6', \fBtrue\fP"
.br
.ti -1c
.RI "const \fBENVIRON\fP 'product', \fBtrue\fP"
.br
.ti -1c
.RI "const \fBFAILED\fP 512, \fBtrue\fP"
.br
.ti -1c
.RI "const \fBMODULE\fP 515, \fBtrue\fP"
.br
.ti -1c
.RI "const \fBCONTROLLER\fP 516, \fBtrue\fP"
.br
.ti -1c
.RI "const \fBACTION\fP 517, \fBtrue\fP"
.br
.ti -1c
.RI "const \fBVIEW\fP 518, \fBtrue\fP"
.br
.ti -1c
.RI "const \fBERROR\fP 521, \fBtrue\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const ACTION 517, \fBtrue\fP"

.SS "const CONTROLLER 516, \fBtrue\fP"

.SS "const ENVIRON 'product', \fBtrue\fP"

.SS "const ERROR 521, \fBtrue\fP"

.SS "const FAILED 512, \fBtrue\fP"

.SS "const MODULE 515, \fBtrue\fP"

.SS "const VERSION '3\&.0\&.6', \fBtrue\fP"

.SS "const VIEW 518, \fBtrue\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
