.TH "vendor/jetbrains/phpstorm-stubs/zend/zend_d.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/zend/zend_d.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_SUCCESS\fP 1"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_WAITING\fP 2"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_SUSPENDED\fP 3"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_SCHEDULED\fP 4"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_WAITING_PREDECESSOR\fP 5"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_IN_PROCESS\fP 6"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_EXECUTION_FAILED\fP 7"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_STATUS_LOGICALLY_FAILED\fP 8"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_PRIORITY_LOW\fP 0"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_PRIORITY_NORMAL\fP 1"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_PRIORITY_HIGH\fP 2"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_PRIORITY_URGENT\fP 3"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_POST\fP 1"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_GET\fP 2"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_COOKIE\fP 4"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_SESSION\fP 8"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_RAW_POST\fP 16"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_SERVER\fP 32"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_FILES\fP 64"
.br
.ti -1c
.RI "const \fBJOB_QUEUE_SAVE_ENV\fP 128"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const JOB_QUEUE_PRIORITY_HIGH 2"

.SS "const JOB_QUEUE_PRIORITY_LOW 0"

.SS "const JOB_QUEUE_PRIORITY_NORMAL 1"

.SS "const JOB_QUEUE_PRIORITY_URGENT 3"

.SS "const JOB_QUEUE_SAVE_COOKIE 4"

.SS "const JOB_QUEUE_SAVE_ENV 128"

.SS "const JOB_QUEUE_SAVE_FILES 64"

.SS "const JOB_QUEUE_SAVE_GET 2"

.SS "const JOB_QUEUE_SAVE_POST 1"

.SS "const JOB_QUEUE_SAVE_RAW_POST 16"

.SS "const JOB_QUEUE_SAVE_SERVER 32"

.SS "const JOB_QUEUE_SAVE_SESSION 8"

.SS "const JOB_QUEUE_STATUS_EXECUTION_FAILED 7"

.SS "const JOB_QUEUE_STATUS_IN_PROCESS 6"

.SS "const JOB_QUEUE_STATUS_LOGICALLY_FAILED 8"

.SS "const JOB_QUEUE_STATUS_SCHEDULED 4"

.SS "const JOB_QUEUE_STATUS_SUCCESS 1"

.SS "const JOB_QUEUE_STATUS_SUSPENDED 3"

.SS "const JOB_QUEUE_STATUS_WAITING 2"

.SS "const JOB_QUEUE_STATUS_WAITING_PREDECESSOR 5"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
