.TH "vendor/jetbrains/phpstorm-stubs/ZendUtils/ZendUtils.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/ZendUtils/ZendUtils.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBzem_get_extension_info_by_id\fP ()"
.br
.ti -1c
.RI "\fBzem_get_extension_info_by_name\fP ()"
.br
.ti -1c
.RI "\fBzem_get_extensions_info\fP ()"
.br
.ti -1c
.RI "\fBzem_get_license_info\fP ()"
.br
.ti -1c
.RI "\fBzend_is_configuration_changed\fP ()"
.br
.ti -1c
.RI "\fBzend_set_configuration_changed\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "zem_get_extension_info_by_id ()"

.SS "zem_get_extension_info_by_name ()"

.SS "zem_get_extensions_info ()"

.SS "zem_get_license_info ()"

.SS "zend_is_configuration_changed ()"

.SS "zend_set_configuration_changed ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
