.TH "vendor/jetbrains/phpstorm-stubs/zmq/zmq.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/zmq/zmq.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBZMQ\fP"
.br
.ti -1c
.RI "class \fBZMQContext\fP"
.br
.ti -1c
.RI "class \fBZMQSocket\fP"
.br
.ti -1c
.RI "class \fBZMQPoll\fP"
.br
.ti -1c
.RI "class \fBZMQDevice\fP"
.br
.ti -1c
.RI "class \fBZMQException\fP"
.br
.ti -1c
.RI "class \fBZMQContextException\fP"
.br
.ti -1c
.RI "class \fBZMQSocketException\fP"
.br
.ti -1c
.RI "class \fBZMQPollException\fP"
.br
.ti -1c
.RI "class \fBZMQDeviceException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
