.TH "vendor/jetbrains/phpstorm-stubs/zookeeper/zookeeper.php" 3 "Sat Sep 26 2020" "Safaricom SDP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jetbrains/phpstorm-stubs/zookeeper/zookeeper.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBZookeeper\fP"
.br
.ti -1c
.RI "class \fBZookeeperException\fP"
.br
.ti -1c
.RI "class \fBZookeeperOperationTimeoutException\fP"
.br
.ti -1c
.RI "class \fBZookeeperConnectionException\fP"
.br
.ti -1c
.RI "class \fBZookeeperMarshallingException\fP"
.br
.ti -1c
.RI "class \fBZookeeperAuthenticationException\fP"
.br
.ti -1c
.RI "class \fBZookeeperSessionException\fP"
.br
.ti -1c
.RI "class \fBZookeeperNoNodeException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Safaricom SDP from the source code\&.
