<?php


/**
 * Bulk SMS
 *
 * @author Phelix Juma <jumaphelix@kuzalab.com>
 * @copyright (c) 2020, Kuza Lab
 * @package Kuzalab
 */

namespace Phelix\SafaricomSDP;



final class BulkSMS {

    /**
     * @var SDP
     */
    private $SDP;

    /**
     * Subscription constructor.
     * @param SDP $SDP
     */
    public function __construct(SDP $SDP) {
        $this->SDP = $SDP;
    }

    /**
     * Send Bulk SMS to a group of users
     *
     * @param string $requestId Transaction id generated by client for tracking purposes (alphanumeric)
     * @param string $username Username allocated by the SDP to the partner after successful registration.
     * @param string $packageId The id of the campaign package as issued upon successful registration
     * @param string $originatingAddress Originating address assigned to partner after successful registration.
     * @param array $recipients The list of phone numbers to send the request to. Format is 7.... (no '0' and no country code)
     * @param string $message Content of the SMS to be sent to user.
     * @param string $callback URL of the CP App for receiving status report.
     * @return array
     */
    public function sendSMS($requestId, $username, $packageId, $originatingAddress, $recipients, $message, $callback) {

        $body =  [
            "timeStamp" => $this->SDP->generateTimestamp(),
            "dataSet"   => [
                [
                    "userName"          => $username,
                    "channel"           => "sms",
                    "packageId"         => $packageId,
                    "oa"                => $originatingAddress,
                    "msisdn"            => implode(",", $recipients),
                    "message"           => $message,
                    "uniqueId"          => $requestId,
                    "actionResponseURL" => $callback
                ]
            ]
        ];

        $response = $this->SDP->request->request("post", "public/CMS/bulksms", $this->SDP->token, $body);

        return Utils::getResponse($response);
    }


}